#ifndef _CPMAC_H_
#define _CPMAC_H_

#define FILE_DEVICE_CPMAC          0x00000468

#define IOCTL_CODE_BASE           3000


// define the IOCTRL code passed to CPC_IOControl
#define IOCTL_CPMAC_SET_MAC \
	CTL_CODE(FILE_DEVICE_CPMAC, IOCTL_CODE_BASE + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_CPMAC_GET_MAC \
	CTL_CODE(FILE_DEVICE_CPMAC, IOCTL_CODE_BASE + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_CPMAC_DELETE_MAC \
	CTL_CODE(FILE_DEVICE_CPMAC, IOCTL_CODE_BASE + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif


