/******************************************************************************
 CVTE Limited.

 Copyright (c) 2014 CVTE company.

 Author Wu haoheng 2014

 All rights reserved.

******************************************************************************/

#ifndef _CVTE_IOCTL_H
#define _CVTE_IOCTL_H

#ifndef METHOD_BUFFERED
#define METHOD_BUFFERED                 0
#endif

#ifndef FILE_ANY_ACCESS
#define FILE_ANY_ACCESS                 0
#endif

#ifndef CTL_CODE
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)
#endif

//
// Define the CVTE reserved IoCtl basic code
//
#ifndef FILE_DEVICE_CVTE_IOCTL
#define FILE_DEVICE_CVTE_IOCTL		0X00008000
#endif
#ifndef FILE_DEVICE_IOCTL_OFFSET
#define FILE_DEVICE_IOCTL_OFFSET	0x00000800
#endif

//
// Define the specific IoCtl
//
#ifndef FILE_DEVICE_OEM_SECTOR
#define FILE_DEVICE_OEM_SECTOR		(FILE_DEVICE_CVTE_IOCTL + 0)
#endif
#ifndef FILE_DEVICE_TW8836
#define FILE_DEVICE_TW8836          (FILE_DEVICE_CVTE_IOCTL + 1)
#endif
#ifndef FILE_DEVICE_LED
#define FILE_DEVICE_LED             (FILE_DEVICE_CVTE_IOCTL + 2)
#endif
#ifndef FILE_DEVICE_GPIO
#define FILE_DEVICE_GPIO            (FILE_DEVICE_CVTE_IOCTL + 3)
#endif
#ifndef FILE_DEVICE_UPD
#define FILE_DEVICE_UPD           	(FILE_DEVICE_CVTE_IOCTL + 4)
#endif

#ifndef FILE_DEVICE_GESTURE
#define FILE_DEVICE_GESTURE         (FILE_DEVICE_CVTE_IOCTL + 5)
#endif

#ifndef FILE_DEVICE_CSECURE
#define FILE_DEVICE_CSECURE         (FILE_DEVICE_CVTE_IOCTL + 6)
#endif
//
// Define the specific operations
//
#define OEMCONFIG_IOCTL_SET_WHOLE_OEMSECTOR             CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_GET_WHOLE_OEMSECTOR             CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_VERSION_ID	                CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_SET_UPDATE_FLAG                 CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_UPDATE_TYPE                 CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_UPDATE_TYPE                 CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_VERSION_TYPE                CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_VERSION_TYPE                CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 7, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_TRACE_TYPE                  CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 8, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_TRACE_TYPE                  CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 9, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_POWER_STATUS                CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 10, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_POWER_STATUS                CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 11, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_RV_CHANNEL                  CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 12, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_RV_CHANNEL                  CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 13, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_LCD_GAMMA                   CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 14, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_LCD_GAMMA                   CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 15, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_HW_UUID                     CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 16, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_CLEAR_UPDATE_FLAG               CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 17, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_COLOR_SIGNAL                CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 18, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_COLOR_SIGNAL                CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 19, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_FUNCTION_MOUSE_CURSOR       CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 20, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_FUNCTION_MOUSE_CURSOR       CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 21, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_GET_FUNCTION_DYNAMIC_LOGO       CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 22, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define OEMCONFIG_IOCTL_SET_FUNCTION_DYNAMIC_LOGO       CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 23, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define OEMCONFIG_IOCTL_SET_UPDATE_FONT_FLAG            CTL_CODE(FILE_DEVICE_OEM_SECTOR, FILE_DEVICE_IOCTL_OFFSET + 24, METHOD_BUFFERED, FILE_ANY_ACCESS)

//
// Define GPIO specific operations
//
#define GPIO_IOCTL_OUTPUT_ENABLE                        CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_OUTPUT_DISABLE                       CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_OUTPUT_ONE                           CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_OUTPUT_ZERO                          CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_PAD_EN_SET                           CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_PAD_EN_CLR                           CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_READ_INPUT                           CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_PULL_UP                              CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_PULL_DOWN                            CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 8, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GPIO_IOCTL_CLR_PULL                             CTL_CODE(FILE_DEVICE_GPIO, FILE_DEVICE_IOCTL_OFFSET + 9, METHOD_BUFFERED, FILE_ANY_ACCESS)


//
// Define tw8836 specific operations
//
#define TW8836_IOCTL_HW_RESET                   CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TW8836_IOCTL_SW_RESET                   CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TW8836_IOCTL_ACTIVATE_CHANNEL           CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TW8836_IOCTL_CHANGE_VIDEOIN_CHANNEL     CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TW8836_IOCTL_POWER_CONTROL              CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TW8836_IOCTL_GET_INPUT_STANDARD         CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TW8836_IOCTL_GET_COLOR_EFFECT           CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TW8836_IOCTL_SET_COLOR_EFFECT           CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TW8836_IOCTL_POWER_QUERY              	CTL_CODE(FILE_DEVICE_TW8836, FILE_DEVICE_IOCTL_OFFSET + 8, METHOD_BUFFERED, FILE_ANY_ACCESS)

//
// Define LED specific operations
//
#define LED_IOCTL_CHANGE_WORK_MODE              CTL_CODE(FILE_DEVICE_LED, FILE_DEVICE_IOCTL_OFFSET + 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define LED_IOCTL_SET_LEDGROUP_IREF             CTL_CODE(FILE_DEVICE_LED, FILE_DEVICE_IOCTL_OFFSET + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define LED_IOCTL_SET_LEDGROUP_PWM              CTL_CODE(FILE_DEVICE_LED, FILE_DEVICE_IOCTL_OFFSET + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define LED_IOCTL_SET_LED_IREF                  CTL_CODE(FILE_DEVICE_LED, FILE_DEVICE_IOCTL_OFFSET + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define LED_IOCTL_SET_LED_PWM                   CTL_CODE(FILE_DEVICE_LED, FILE_DEVICE_IOCTL_OFFSET + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define LED_IOCTL_SET_ALLLED_ON                 CTL_CODE(FILE_DEVICE_LED, FILE_DEVICE_IOCTL_OFFSET + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define LED_IOCTL_SET_ALLLED_OFF                CTL_CODE(FILE_DEVICE_LED, FILE_DEVICE_IOCTL_OFFSET + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define LED_IOCTL_SET_CHANNEL                   CTL_CODE(FILE_DEVICE_LED, FILE_DEVICE_IOCTL_OFFSET + 7, METHOD_BUFFERED, FILE_ANY_ACCESS)

//
// Define Store sector operations
//
#define IOCTL_UPD_STORE_LOGO                    CTL_CODE(FILE_DEVICE_UPD, FILE_DEVICE_IOCTL_OFFSET + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UPD_STORE_EBOOT                   CTL_CODE(FILE_DEVICE_UPD, FILE_DEVICE_IOCTL_OFFSET + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UPD_STORE_IMAGE                   CTL_CODE(FILE_DEVICE_UPD, FILE_DEVICE_IOCTL_OFFSET + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UPD_LOGO                          CTL_CODE(FILE_DEVICE_UPD, FILE_DEVICE_IOCTL_OFFSET + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UPD_EBOOT                         CTL_CODE(FILE_DEVICE_UPD, FILE_DEVICE_IOCTL_OFFSET + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UPD_STORE_IMAGE_SECTOR            CTL_CODE(FILE_DEVICE_UPD, FILE_DEVICE_IOCTL_OFFSET + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UPD_RES                           CTL_CODE(FILE_DEVICE_UPD, FILE_DEVICE_IOCTL_OFFSET + 7, METHOD_BUFFERED, FILE_ANY_ACCESS)

//
// Define Gesture operations
//
#define PAC_IOCTL_SET_OPERATION_DISTANCE         CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_SET_OPERATION_SENSITIVITY      CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_SET_OPERATION_WAVE             CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_SET_OPERATION_ROTATE           CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_SET_OPERATION_NOMOTION         CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_SET_OPERATION_NOOBJECT         CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_GET_OPERATION_DISTANCE         CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_GET_OPERATION_SENSITIVITY      CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_GET_OPERATION_WAVE             CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 8, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_GET_OPERATION_ROTATE           CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 9, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_GET_OPERATION_NOMOTION         CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 10, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_GET_OPERATION_NOOBJECT         CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 11, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PAC_IOCTL_GET_OBJECT_INFO                CTL_CODE(FILE_DEVICE_GESTURE, FILE_DEVICE_IOCTL_OFFSET + 12, METHOD_BUFFERED, FILE_ANY_ACCESS)

//
// Define CSecure operations
//
#define IOCTL_CSECURE_SET_MAC                    CTL_CODE(FILE_DEVICE_CSECURE, FILE_DEVICE_IOCTL_OFFSET + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CSECURE_GET_MAC                    CTL_CODE(FILE_DEVICE_CSECURE, FILE_DEVICE_IOCTL_OFFSET + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CSECURE_DELETE_MAC                 CTL_CODE(FILE_DEVICE_CSECURE, FILE_DEVICE_IOCTL_OFFSET + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CSECURE_SET_CA                     CTL_CODE(FILE_DEVICE_CSECURE, FILE_DEVICE_IOCTL_OFFSET + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CSECURE_GET_CA                     CTL_CODE(FILE_DEVICE_CSECURE, FILE_DEVICE_IOCTL_OFFSET + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CSECURE_DELETE_CA                  CTL_CODE(FILE_DEVICE_CSECURE, FILE_DEVICE_IOCTL_OFFSET + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)


#endif
