//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LightningUI.rc
//
#define IDS_APP_TITLE                   1
#define IDC_LIGHTNINGUI                 2
#define IDI_LIGHTNINGUI                 3
#define IDS_TITLE_MIRRORLINK            3
#define IDS_TITLE_RADIO                 10
#define IDS_TITLE_BLUETOOTH             11
#define IDS_TITLE_MEDIA                 12
#define IDS_TITLE_PHONELINK             13
#define IDS_TITLE_NAVI                  14
#define IDS_TITLE_TV                    15
#define IDS_TITLE_MHL                   16
#define IDS_TITLE_DISK                  17
#define IDS_TITLE_AUX                   18
#define IDS_TITLE_IPOD                  19
#define IDS_TITLE_SETTINGS              20
#define IDS_TITLE_VEHICLEINFO           21
#define IDS_TITLE_MUSIC                 22
#define IDS_TITLE_VIDEO                 23
#define IDS_TITLE_IMAGE                 24
#define IDS_TITLE_TIME                  25
#define IDS_TITLE_DATE                  26
#define IDS_TITLE_USB                   27
#define IDS_TITLE_SD                    28
#define IDS_TITLE_CD                    29
#define IDS_TITLE_DVD                   30
#define IDS_TITLE_APPS                  31
#define IDS_UNKNOWN                     32
#define IDS_SUNDAY                      33
#define IDS_MONDAY                      34
#define IDS_TUESDAY                     35
#define IDS_WEDNESDAY                   36
#define IDS_THURSDAY                    37
#define IDS_FRIDAY                      38
#define IDS_SATURDAY                    39
#define IDS_JANUARY                     40
#define IDS_FEBRUARY                    41
#define IDS_MARCH                       42
#define IDS_APRIL                       43
#define IDS_MAY                         44
#define IDS_JUNE                        45
#define IDS_JULY                        46
#define IDS_AUGUST                      47
#define IDS_SEPTEMBER                   48
#define IDS_OCTOBER                     49
#define IDS_NOVEMBER                    50
#define IDS_DECEMBER                    51
#define IDS_ON                          52
#define IDS_OFF                         53
#define IDS_YES                         54
#define IDS_NO                          55
#define IDS_OK                          56
#define IDS_CANCEL                      57
#define IDS_RESET                       58
#define IDS_CONFIRM                     59
#define IDS_CONNECTING                  60
#define IDS_CONNECTED                   61
#define IDS_LOADING                     62
#define IDS_TITLE_REARVIEW              63
#define IDS_PARKING_NOTICE              64
#define IDS_NO_SIGNAL                   65
#define IDS_CAN_BELT                    66
#define IDS_CAN_OUTSIDE_TEMP            67
#define IDS_CAN_BATTERY                 68
#define IDS_CAN_OIL                     69
#define IDS_CAN_HANDBRAKE               70
#define IDS_CAN_TRIP                    71
#define IDS_CAN_ENGIN_SPEED             72
#define IDS_CAN_CLEANINGWATER           73
#define IDS_CAN_VELOCITY                74
#define IDS_CAN_AIR                     75
#define IDS_CAN_BODY                    76
#define IDS_CAN_RADAR                   77
#define IDS_CAN_HANDBRAKE_UNRELEASED    78
#define IDS_SETTINGS_HIGH               79
#define IDS_SETTINGS_LOW                80
#define IDS_SETTINGS_NORMAL             81
#define IDS_PHONELINK_MAIN_PROMPT       82
#define IDS_PHONELINK_INSTALLING        83
#define IDS_PHONELINK_INSTALL_OK        84
#define IDS_PHONELINK_NO_USB_DEBUG      85
#define IDS_PHONELINK_CONNECTING        86
#define IDS_MHL_MAIN_PROMPT             87
#define IDS_MHL_CONNECTING              88
#define IDS_MHL_CONNECTED               89
#define IDS_MHL_WAITING                 90
#define IDS_TITLE_PHONE                 91
#define IDS_DEVICE_REMOVE               92
#define IDS_DEVICE_INSERT               93
#define IDS_DEVICE_RESIDENTFLASH        94
#define IDS_DEVICE_IPOD                 95
#define IDS_DEVICE_USB                  96
#define IDS_DEVICE_BT                   97
#define IDS_DEVICE_SD                   98
#define IDS_DEVICE_CD                   99
#define IDS_DEVICE_LINEIN_FRONT         100
#define IDS_DEVICE_LINEIN_REAR          101
#define IDS_NO_MEDIA_FILES              102
#define IDS_WARNING                     103
#define IDS_CANNOT_WATCH_VIDEO          104
#define IDS_BROWSING_ACTIVE             105
#define IDS_LIBRARY_MENU_ALBUMS         106
#define IDS_LIBRARY_MENU_ARTISTS        107
#define IDS_LIBRARY_MENU_COMPOSERS      108
#define IDS_LIBRARY_MENU_GENRES         109
#define IDS_LIBRARY_MENU_EXPLORE        110
#define IDS_LIBRARY_MENU_TRACKS         111
#define IDS_LIBRARY_MENU_PLAYLISTS      112
#define IDS_LIBRARY_MENU_PODCASTS       113
#define IDS_LIBRARY_MENU_EPISODES       114
#define IDS_LIBRARY_MENU_AUDIOBOOKS     115
#define IDS_NOWPLAYING_PLAYING          116
#define IDS_NOWPLAYING_INVALIDMEDIA     117
#define IDS_TITLE_HOME                  118
#define IDS_TITLE_NOWPLAYING            119
#define IDS_SEARCH                      120
#define IDS_LOCATION_MOBILE             121
#define IDS_LOCATION_WORK               122
#define IDS_LOCATION_HOME               123
#define IDS_DISCONNECTING               124
#define IDS_DISCONNECTED                125
#define IDS_CALL                        126
#define IDS_DISCONNECT_DEVICE           127
#define IDS_CS_HOLD                     128
#define IDS_CS_DIALING                  129
#define IDS_CS_INCOMING_CALL            130
#define IDS_CS_WAITING_CALL             131
#define IDS_DOWNLOADING                 132
#define IDS_CAN_BELT_UNBUCKLED          133
#define IDS_STEREO                      134
#define IDS_MONO                        135
#define IDS_LOC                         136
#define IDS_FAVORITE                    137
#define IDS_PAIRED                      138
#define IDS_DOWNLOAD                    139
#define IDS_DEVICE_MGR                  140
#define IDS_NO_DEVICE_PAIRED            141
#define IDS_PHONECORE_FINDME_NOTE       142
#define IDS_NO_DEVICE_FOUND             143
#define IDS_SETTING_GENERAL             144
#define IDS_SETTING_AUDIO               145
#define IDS_SETTING_BLUETOOTH           146
#define IDS_SETTING_RADIO               147
#define IDS_SETTING_ABOUT               148
#define IDS_SETTING_HANDBRAKE_TEST      149
#define IDS_SETTING_REVERSE_POLAR       150
#define IDS_SETTING_LAMP_CONTROL        151
#define IDS_SETTING_DATE_AND_TIME       152
#define IDS_SETTING_DATE                153
#define IDS_SETTING_TIME                154
#define IDS_SETTING_24H_MODE            155
#define IDS_SETTING_TIME_AUTO_ADJUST    156
#define IDS_SETTING_NAVIGATION          157
#define IDS_SETTING_NAVI_LAUNCH_LOCATION 158
#define IDS_SETTING_NAVI_SPEECH         159
#define IDS_SETTING_LANGUAGE            160
#define IDS_SETTING_LANG_CHN_SIM        161
#define IDS_SETTING_LANG_CHN_TRA        162
#define IDS_SETTING_LANG_ENGLISH        163
#define IDS_SETTING_NAVI_SPEECH_ALWAYS  164
#define IDS_SETTING_NAVI_SPEECH_CLOSED  165
#define IDS_SETTING_NAVI_SPEECH_MAP     166
#define IDS_SETTING_MUTE                167
#define IDS_SETTING_LOUDNESS            168
#define IDS_SETTING_VOLUME_VELOCITY_ADJUST 169
#define IDS_SETTING_AUDIO_EFFECT        170
#define IDS_SETTING_CLASSIC             171
#define IDS_SETTING_POP                 172
#define IDS_SETTING_ROCK                173
#define IDS_SETTING_JAZZ                174
#define IDS_SETTING_USER                175
#define IDS_SETTING_EQ                  176
#define IDS_SETTING_BAL_FAD             177
#define IDS_SETTING_LOW                 178
#define IDS_SETTING_MID                 179
#define IDS_SETTING_HIGH                180
#define IDS_SETTING_BT_POWER            181
#define IDS_SETTING_BT_DEVICE_NAME      182
#define IDS_SETTING_BT_PAIR_PIN         183
#define IDS_SETTING_BT_AUTO_ANSWER      184
#define IDS_SETTING_BT_AUTO_DOWNLOAD_PB 185
#define IDS_SETTING_RADIO_SEEK_QUALITY  186
#define IDS_SETTING_RADIO_FM            187
#define IDS_SETTING_RADIO_AM            188
#define IDS_SETTING_RADIO_RESET_SEEK_QUALITY 189
#define IDS_SETTING_RADIO_REGION        190
#define IDS_SETTING_EUROPE              191
#define IDS_SETTING_USA                 192
#define IDS_SETTING_EASTERN_EUROPE      193
#define IDS_SETTING_JAPAN               194
#define IDS_SETTING_RADIO_RDS_SWITCH    195
#define IDS_SETTING_OS_VERSION          196
#define IDS_SETTING_SOFTWARE_VERSION    197
#define IDS_SETTING_MCU_VERSION         198
#define IDS_SETTING_HARDWARE_VERSION    199
#define IDS_VEHICLE_DRIVE               200
#define IDS_VEHICLE_AC                  201
#define IDS_VEHICLE_BODY                202
#define IDS_VEHICLE_RADAR               203
#define IDS_NO_MEDIA_DEVICE             204
#define IDS_INPUT_NEW_DEVICE_NAME       205
#define IDS_INPUT_NEW_PAIR_PIN          206
#define IDS_CALL_HISTORY                207
#define IDS_CONTACT                     208
#define IDS_SEARCHING                   209
#define IDS_CS_CONNECTED                210
#define IDS_NOT_CONNECTED               211
#define IDS_BT_CONNECT_SETTING          212
#define IDS_BT_PAIRING                  213
#define IDS_BT_DEVICE_PAIRED            214
#define IDS_RESET_TO_TAKE_EFFECT        215
#define IDS_SETTING_IDLE_SCREEN         216
#define IDS_CLOCK_ANALOG                217
#define IDS_CLOCK_DIGITAL               218
#define IDS_NONE                        219
#define IDS_MEDIA_BROWSE_FOLDER         220
#define IDS_MEDIA_BROWSE_TRACK          221
#define IDS_MEDIA_BROWSE_PARENT_FOLDER  222
#define IDS_SETTING_CAMERA_TYPE         223
#define IDS_UPDATE                      224
#define IDS_MCU_UPDATE_CONFIRM          225
#define IDS_MCU_UPDATE_PROMPT           226
#define IDS_MCU_UPDATING                227
#define IDS_MCU_UPDATING_ALERT          228
#define IDS_MCU_UPDATING_INVALID_FILE   229
#define IDS_MCU_UPDATE_SUCCEED          230
#define IDS_MCU_UPDATE_FAILED           231
#define IDS_SETTING_UI                  232
#define IDS_SETTING_UI_SKIN             233
#define IDS_SETTING_SUBWOOFER           234
#define IDS_SETTING_UI_BACKGROUND       235
#define IDS_RETURN                      236
#define IDS_BT_STREAMING_AUDIO          237
#define IDS_BT_STREAMING_AUDIO_TERMINATE 238
#define IDS_STRANGER                    239
#define IDS_SETTING_UI_FACTORY          240
#define IDS_SETTING_UI_RESTORE_FACTORY_SETTINGS 241
#define IDS_SETTING_UI_DEFAULT          242
#define IDS_SETTING_VOLUME              243
#define IDS_UPDATE_PROMPT_0             244
#define IDS_UPDATE_PROMPT_1             245
#define IDS_UPDATE_PROMPT_2             246
#define IDS_UPDATE_PROMPT_3             247
#define IDS_NO_LISTITEM                 248
#define IDS_SETTING_UI_BACK_LUMIN       249
#define IDS_SETTING_KEY_BEEP            250
#define IDS_CARPLAY_MAIN_PROMPT         251
#define IDS_SETTING_DISPLAY             252
#define IDS_SETTING_LED_RED             253
#define IDS_SETTING_LED_GREEN           254
#define IDS_SETTING_LED_BLUE            255
#define IDS_SETTING_LCD_GAMMA           256
#define IDS_SETTING_BLUR_EFFECT         257
#define IDS_SETTING_LED_BRIGHTNESS      258
#define IDS_RESET_DEFAULT               259
#define IDS_ACTIVATE_PROMPT_0           260
#define IDS_SETTING_VOL_NAVI_SPEECH     261
#define IDS_SETTING_DRIVE_TYPE          262
#define IDS_SETTING_DRIVE_LEFT          263
#define IDS_SETTING_DRIVE_RIGHT         264
#define IDS_SETTING_BT_RINGTONE         265
#define IDS_SETTING_ADVANCED            266
#define IDS_PHONELINK_CONNECT_FAILED    267
#define IDS_SETTING_TIMEZONE            268
#define IDS_SETTING_BT_AUTO_CONNECT     269
#define IDS_SETTING_PANEL_LIGHT         270
#define IDS_SETTING_PANEL_LIGHT_DISC    271
#define IDS_SETTING_PANEL_LIGHT_COLOR   272
#define IDS_SETTING_PANEL_LIGHT_BRIGHTNESS 273
#define IDS_DIAL                        274
#define IDS_SETTING_KOREA               275
#define IDS_SETTING_ADVANCE             276
#define IDS_SETTING_STEER_WHEEL         277
#define IDS_SETTING_STEER_WHEEL_DESC    278
#define IDS_SETTING_STEER_WHEEL_PROMPT  279
#define IDS_SETTING_STEER_WHEEL_RECALIBRATE 280
#define IDS_IMAGE_UPDATING              281
#define IDS_IMAGE_UPDATE_CONFIRM        282
#define IDS_RESTART_SYSTEM              283
#define IDS_SETTING_RESET               284
#define IDS_RADIO_SOUTHAMERICA          284
#define IDS_SETTING_SOUTHAMERICA        284
#define IDS_SETTING_HARDWARE_ID         285
#define IDS_SETTING_REARVIEW_SETTING    286
#define IDS_SETTING_REARVIEW_TITLE      287
#define IDS_SETTING_LED_ANIM_EFFECT     288
#define IDS_SETTING_ENTER_PASSWORD      289
#define IDS_SETTING_SCREEN_BRIGHTNESS   290
#define IDS_CONFIRM_DOWNLOAD_PB         291
#define IDS_SETTING_TIME_AUTO_ADJUST_DLST 292
#define IDS_SETTING_ENABLE_REAR_VOL_CONTROL 293
#define IDS_SETTING_STW_CALIBRATE       294
#define IDS_AUX_PLAYING                 295
#define IDS_AUX_TIP2                    296
#define IDS_CONFIRM_DOWNLOAD_CALLHISTORY 297
#define IDS_SETTING_WHEEL               298
#define IDS_SETTING_RADIO_RBDS_SWITCH   299
#define IDS_SETTING_AUDIO_SUBWOOFER_FREQ 300
#define IDS_SETTING_DISPLAY_TITLE_LCD   301
#define IDS_BT_PHONEBOOK_SYNC           302
#define IDS_BT_PHONEBOOK_BACK           303
#define IDS_BT_PHONEBOOK_FIRST_NAME_FIRST 304
#define IDS_SETTING_CHARGING_ONLY       305
#define IDS_TAIWAN                      306
#define IDS_SOUTH_AMERICA               307
#define IDS_ARABIA_AUSTRALIA            308
#define IDS_LATIN_AMERICA               309
#define IDS_MIDDLE_EAST                 310
#define IDS_AUST                        311
#define IDS_BRAZIL                      312
#define IDS_RUSSIA                      313
#define IDS_SETTING_ANDROID_TYPE        314
#define IDS_USB_HUB_UNSUPPORTED         315
#define IDS_AUTO_LAUNCH                 316
#define IDS_DAY                         317
#define IDS_NIGHT                       318
#define IDS_STW_VOL_ADD                 319
#define IDS_STW_VOL_SUB                 320
#define IDS_STW_MUTE                    321
#define IDS_STW_PREVIOUS                322
#define IDS_STW_NEXT                    323
#define IDS_STW_SEEK                    324
#define IDS_STW_CALL                    325
#define IDS_STW_HANGUP                  326
#define IDS_STW_SPEECH                  327
#define IDS_STW_POWER                   328
#define IDS_STW_MODE                    329
#define IDS_STW_NAVI                    330
#define IDS_STW_UNDEFINE                331
#define IDS_STW_ACTIVATED               332
#define IDS_AA_NOTE1                    333
#define IDS_AA_NOTE2                    334
#define IDS_AA_NOTE3                    335
#define IDS_MHZ                         336
#define IDS_KHZ                         337
#define IDS_KEYPAD         				338
#define IDS_HANGUP         				339
#define IDS_ANSWER         				340
#define IDS_PRIVACY         			341
#define IDS_HANDS_FREE         			342
#define IDS_APP_TITLE_CN_TRA            2001
#define IDC_LIGHTNINGUI_CN_TRA          2002
#define IDS_STRING2003                  2003
#define IDS_TITLE_RADIO_CN_TRA          2010
#define IDS_TITLE_BLUETOOTH_CN_TRA      2011
#define IDS_TITLE_MEDIA_CN_TRA          2012
#define IDS_TITLE_PHONELINK_CN_TRA      2013
#define IDS_TITLE_NAVI_CN_TRA           2014
#define IDS_TITLE_TV_CN_TRA             2015
#define IDS_TITLE_MHL_CN_TRA            2016
#define IDS_TITLE_DISK_CN_TRA           2017
#define IDS_TITLE_AUX_CN_TRA            2018
#define IDS_TITLE_IPOD_CN_TRA           2019
#define IDS_TITLE_SETTINGS_CN_TRA       2020
#define IDS_TITLE_VEHICLEINFO_CN_TRA    2021
#define IDS_TITLE_MUSIC_CN_TRA          2022
#define IDS_TITLE_VIDEO_CN_TRA          2023
#define IDS_TITLE_IMAGE_CN_TRA          2024
#define IDS_TITLE_TIME_CN_TRA           2025
#define IDS_TITLE_DATE_CN_TRA           2026
#define IDS_TITLE_USB_CN_TRA            2027
#define IDS_TITLE_SD_CN_TRA             2028
#define IDS_TITLE_CD_CN_TRA             2029
#define IDS_TITLE_DVD_CN_TRA            2030
#define IDS_TITLE_APPS_CN_TRA           2031
#define IDS_UNKNOWN_CN_TRA              2032
#define IDS_SUNDAY_CN_TRA               2033
#define IDS_MONDAY_CN_TRA               2034
#define IDS_TUESDAY_CN_TRA              2035
#define IDS_WEDNESDAY_CN_TRA            2036
#define IDS_THURSDAY_CN_TRA             2037
#define IDS_FRIDAY_CN_TRA               2038
#define IDS_SATURDAY_CN_TRA             2039
#define IDS_JANUARY_CN_TRA              2040
#define IDS_FEBRUARY_CN_TRA             2041
#define IDS_MARCH_CN_TRA                2042
#define IDS_APRIL_CN_TRA                2043
#define IDS_MAY_CN_TRA                  2044
#define IDS_JUNE_CN_TRA                 2045
#define IDS_JULY_CN_TRA                 2046
#define IDS_AUGUST_CN_TRA               2047
#define IDS_SEPTEMBER_CN_TRA            2048
#define IDS_OCTOBER_CN_TRA              2049
#define IDS_NOVEMBER_CN_TRA             2050
#define IDS_DECEMBER_CN_TRA             2051
#define IDS_ON_CN_TRA                   2052
#define IDS_OFF_CN_TRA                  2053
#define IDS_YES_CN_TRA                  2054
#define IDS_NO_CN_TRA                   2055
#define IDS_OK_CN_TRA                   2056
#define IDS_CANCEL_CN_TRA               2057
#define IDS_RESET_CN_TRA                2058
#define IDS_CONFIRM_CN_TRA              2059
#define IDS_CONNECTING_CN_TRA           2060
#define IDS_CONNECTED_CN_TRA            2061
#define IDS_LOADING_CN_TRA              2062
#define IDS_TITLE_REARVIEW_CN_TRA       2063
#define IDS_PARKING_NOTICE_CN_TRA       2064
#define IDS_NO_SIGNAL_CN_TRA            2065
#define IDS_CAN_BELT_CN_TRA             2066
#define IDS_CAN_OUTSIDE_TEMP_CN_TRA     2067
#define IDS_CAN_BATTERY_CN_TRA          2068
#define IDS_CAN_OIL_CN_TRA              2069
#define IDS_CAN_HANDBRAKE_CN_TRA        2070
#define IDS_CAN_TRIP_CN_TRA             2071
#define IDS_CAN_ENGIN_SPEED_CN_TRA      2072
#define IDS_CAN_CLEANINGWATER_CN_TRA    2073
#define IDS_CAN_VELOCITY_CN_TRA         2074
#define IDS_CAN_AIR_CN_TRA              2075
#define IDS_CAN_BODY_CN_TRA             2076
#define IDS_CAN_RADAR_CN_TRA            2077
#define IDS_CAN_HANDBRAKE_UNRELEASED_CN_TRA 2078
#define IDS_SETTINGS_HIGH_CN_TRA        2079
#define IDS_SETTINGS_LOW_CN_TRA         2080
#define IDS_SETTINGS_NORMAL_CN_TRA      2081
#define IDS_PHONELINK_MAIN_PROMPT_CN_TRA 2082
#define IDS_PHONELINK_INSTALLING_CN_TRA 2083
#define IDS_PHONELINK_INSTALL_OK_CN_TRA 2084
#define IDS_PHONELINK_NO_USB_DEBUG_CN_TRA 2085
#define IDS_PHONELINK_CONNECTING_CN_TRA 2086
#define IDS_MHL_MAIN_PROMPT_CN_TRA      2087
#define IDS_MHL_CONNECTING_CN_TRA       2088
#define IDS_MHL_CONNECTED_CN_TRA        2089
#define IDS_MHL_WAITING_CN_TRA          2090
#define IDS_TITLE_PHONE_CN_TRA          2091
#define IDS_DEVICE_REMOVE_CN_TRA        2092
#define IDS_DEVICE_INSERT_CN_TRA        2093
#define IDS_DEVICE_RESIDENTFLASH_CN_TRA 2094
#define IDS_DEVICE_IPOD_CN_TRA          2095
#define IDS_DEVICE_USB_CN_TRA           2096
#define IDS_DEVICE_BT_CN_TRA            2097
#define IDS_DEVICE_SD_CN_TRA            2098
#define IDS_DEVICE_CD_CN_TRA            2099
#define IDS_DEVICE_LINEIN_FRONT_CN_TRA  2100
#define IDS_DEVICE_LINEIN_REAR_CN_TRA   2101
#define IDS_NO_MEDIA_FILES_CN_TRA       2102
#define IDS_WARNING_CN_TRA              2103
#define IDS_CANNOT_WATCH_VIDEO_CN_TRA   2104
#define IDS_BROWSING_ACTIVE_CN_TRA      2105
#define IDS_LIBRARY_MENU_ALBUMS_CN_TRA  2106
#define IDS_LIBRARY_MENU_ARTISTS_CN_TRA 2107
#define IDS_LIBRARY_MENU_COMPOSERS_CN_TRA 2108
#define IDS_LIBRARY_MENU_GENRES_CN_TRA  2109
#define IDS_LIBRARY_MENU_EXPLORE_CN_TRA 2110
#define IDS_LIBRARY_MENU_TRACKS_CN_TRA  2111
#define IDS_LIBRARY_MENU_PLAYLISTS_CN_TRA 2112
#define IDS_LIBRARY_MENU_PODCASTS_CN_TRA 2113
#define IDS_LIBRARY_MENU_EPISODES_CN_TRA 2114
#define IDS_LIBRARY_MENU_AUDIOBOOKS_CN_TRA 2115
#define IDS_NOWPLAYING_PLAYING_CN_TRA   2116
#define IDS_NOWPLAYING_INVALIDMEDIA_CN_TRA 2117
#define IDS_TITLE_HOME_CN_TRA           2118
#define IDS_TITLE_NOWPLAYING_CN_TRA     2119
#define IDS_SEARCH_CN_TRA               2120
#define IDS_LOCATION_MOBILE_CN_TRA      2121
#define IDS_LOCATION_WORK_CN_TRA        2122
#define IDS_LOCATION_HOME_CN_TRA        2123
#define IDS_DISCONNECTING_CN_TRA        2124
#define IDS_DISCONNECTED_CN_TRA         2125
#define IDS_CALL_CN_TRA                 2126
#define IDS_DISCONNECT_DEVICE_CN_TRA    2127
#define IDS_CS_HOLD_CN_TRA              2128
#define IDS_CS_DIALING_CN_TRA           2129
#define IDS_CS_INCOMING_CALL_CN_TRA     2130
#define IDS_CS_WAITING_CALL_CN_TRA      2131
#define IDS_DOWNLOADING_CN_TRA          2132
#define IDS_CAN_BELT_UNBUCKLED_CN_TRA   2133
#define IDS_STEREO_CN_TRA               2134
#define IDS_MONO_CN_TRA                 2135
#define IDS_LOC_CN_TRA                  2136
#define IDS_FAVORITE_CN_TRA             2137
#define IDS_PAIRED_CN_TRA               2138
#define IDS_DOWNLOAD_CN_TRA             2139
#define IDS_DEVICE_MGR_CN_TRA           2140
#define IDS_NO_DEVICE_PAIRED_CN_TRA     2141
#define IDS_PHONECORE_FINDME_NOTE_CN_TRA 2142
#define IDS_NO_DEVICE_FOUND_CN_TRA      2143
#define IDS_SETTING_GENERAL_CN_TRA      2144
#define IDS_SETTING_AUDIO_CN_TRA        2145
#define IDS_SETTING_BLUETOOTH_CN_TRA    2146
#define IDS_SETTING_RADIO_CN_TRA        2147
#define IDS_SETTING_ABOUT_CN_TRA        2148
#define IDS_SETTING_HANDBRAKE_TEST_CN_TRA 2149
#define IDS_SETTING_REVERSE_POLAR_CN_TRA 2150
#define IDS_SETTING_LAMP_CONTROL_CN_TRA 2151
#define IDS_SETTING_DATE_AND_TIME_CN_TRA 2152
#define IDS_SETTING_DATE_CN_TRA         2153
#define IDS_SETTING_TIME_CN_TRA         2154
#define IDS_SETTING_24H_MODE_CN_TRA     2155
#define IDS_SETTING_TIME_AUTO_ADJUST_CN_TRA 2156
#define IDS_SETTING_NAVIGATION_CN_TRA   2157
#define IDS_SETTING_NAVI_LAUNCH_LOCATION_CN_TRA 2158
#define IDS_SETTING_NAVI_SPEECH_CN_TRA  2159
#define IDS_SETTING_LANGUAGE_CN_TRA     2160
#define IDS_SETTING_LANG_CHN_SIM_CN_TRA 2161
#define IDS_SETTING_LANG_CHN_TRA_CN_TRA 2162
#define IDS_SETTING_LANG_ENGLISH_CN_TRA 2163
#define IDS_SETTING_NAVI_SPEECH_ALWAYS_CN_TRA 2164
#define IDS_SETTING_NAVI_SPEECH_CLOSED_CN_TRA 2165
#define IDS_SETTING_NAVI_SPEECH_MAP_CN_TRA 2166
#define IDS_SETTING_MUTE_CN_TRA         2167
#define IDS_SETTING_LOUDNESS_CN_TRA     2168
#define IDS_SETTING_VOLUME_VELOCITY_ADJUST_CN_TRA 2169
#define IDS_SETTING_AUDIO_EFFECT_CN_TRA 2170
#define IDS_SETTING_CLASSIC_CN_TRA      2171
#define IDS_SETTING_POP_CN_TRA          2172
#define IDS_SETTING_ROCK_CN_TRA         2173
#define IDS_SETTING_JAZZ_CN_TRA         2174
#define IDS_SETTING_USER_CN_TRA         2175
#define IDS_SETTING_EQ_CN_TRA           2176
#define IDS_SETTING_BAL_FAD_CN_TRA      2177
#define IDS_SETTING_LOW_CN_TRA          2178
#define IDS_SETTING_MID_CN_TRA          2179
#define IDS_SETTING_HIGH_CN_TRA         2180
#define IDS_SETTING_BT_POWER_CN_TRA     2181
#define IDS_SETTING_BT_DEVICE_NAME_CN_TRA 2182
#define IDS_SETTING_BT_PAIR_PIN_CN_TRA  2183
#define IDS_SETTING_BT_AUTO_ANSWER_CN_TRA 2184
#define IDS_SETTING_BT_AUTO_DOWNLOAD_PB_CN_TRA 2185
#define IDS_SETTING_RADIO_SEEK_QUALITY_CN_TRA 2186
#define IDS_SETTING_RADIO_FM_CN_TRA     2187
#define IDS_SETTING_RADIO_AM_CN_TRA     2188
#define IDS_SETTING_RADIO_RESET_SEEK_QUALITY_CN_TRA 2189
#define IDS_SETTING_RADIO_REGION_CN_TRA 2190
#define IDS_SETTING_EUROPE_CN_TRA       2191
#define IDS_SETTING_USA_CN_TRA          2192
#define IDS_SETTING_EASTERN_EUROPE_CN_TRA 2193
#define IDS_SETTING_JAPAN_CN_TRA        2194
#define IDS_SETTING_RADIO_RDS_SWITCH_CN_TRA 2195
#define IDS_SETTING_OS_VERSION_CN_TRA   2196
#define IDS_SETTING_SOFTWARE_VERSION_CN_TRA 2197
#define IDS_SETTING_MCU_VERSION_CN_TRA  2198
#define IDS_SETTING_HARDWARE_VERSION_CN_TRA 2199
#define IDS_VEHICLE_DRIVE_CN_TRA        2200
#define IDS_VEHICLE_AC_CN_TRA           2201
#define IDS_VEHICLE_BODY_CN_TRA         2202
#define IDS_VEHICLE_RADAR_CN_TRA        2203
#define IDS_NO_MEDIA_DEVICE_CN_TRA      2204
#define IDS_INPUT_NEW_DEVICE_NAME_CN_TRA 2205
#define IDS_INPUT_NEW_PAIR_PIN_CN_TRA   2206
#define IDS_CALL_HISTORY_CN_TRA         2207
#define IDS_CONTACT_CN_TRA              2208
#define IDS_SEARCHING_CN_TRA            2209
#define IDS_CS_CONNECTED_CN_TRA         2210
#define IDS_NOT_CONNECTED_CN_TRA        2211
#define IDS_BT_CONNECT_SETTING_CN_TRA   2212
#define IDS_BT_PAIRING_CN_TRA           2213
#define IDS_BT_DEVICE_PAIRED_CN_TRA     2214
#define IDS_RESET_TO_TAKE_EFFECT_CN_TRA 2215
#define IDS_SETTING_IDLE_SCREEN_CN_TRA  2216
#define IDS_CLOCK_ANALOG_CN_TRA         2217
#define IDS_CLOCK_DIGITAL_CN_TRA        2218
#define IDS_NONE_CN_TRA                 2219
#define IDS_MEDIA_BROWSE_FOLDER_CN_TRA  2220
#define IDS_MEDIA_BROWSE_TRACK_CN_TRA   2221
#define IDS_MEDIA_BROWSE_PARENT_FOLDER_CN_TRA 2222
#define IDS_SETTING_CAMERA_TYPE_CN_TRA  2223
#define IDS_UPDATE_CN_TRA               2224
#define IDS_MCU_UPDATE_CONFIRM_CN_TRA   2225
#define IDS_MCU_UPDATE_PROMPT_CN_TRA    2226
#define IDS_MCU_UPDATING_CN_TRA         2227
#define IDS_MCU_UPDATING_ALERT_CN_TRA   2228
#define IDS_MCU_UPDATING_INVALID_FILE_CN_TRA 2229
#define IDS_MCU_UPDATE_SUCCEED_CN_TRA   2230
#define IDS_MCU_UPDATE_FAILED_CN_TRA    2231
#define IDS_SETTING_UI_CN_TRA           2232
#define IDS_SETTING_UI_SKIN_CN_TRA      2233
#define IDS_SETTING_SUBWOOFER_CN_TRA    2234
#define IDS_SETTING_UI_BACKGROUND_CN_TRA 2235
#define IDS_RETURN_CN_TRA               2236
#define IDS_BT_STREAMING_AUDIO_CN_TRA   2237
#define IDS_BT_STREAMING_AUDIO_TERMINATE_CN_TRA 2238
#define IDS_STRANGER_CN_TRA             2239
#define IDS_SETTING_UI_FACTORY_CN_TRA   2240
#define IDS_SETTING_UI_RESTORE_FACTORY_SETTINGS_CN_TRA 2241
#define IDS_SETTING_UI_DEFAULT_CN_TRA   2242
#define IDS_SETTING_VOLUME_CN_TRA       2243
#define IDS_UPDATE_PROMPT_0_CN_TRA      2244
#define IDS_UPDATE_PROMPT_1_CN_TRA      2245
#define IDS_UPDATE_PROMPT_2_CN_TRA      2246
#define IDS_UPDATE_PROMPT_3_CN_TRA      2247
#define IDS_NO_LISTITEM_CN_TRA          2248
#define IDS_SETTING_UI_BACK_LUMIN_CN_TRA 2249
#define IDS_SETTING_KEY_BEEP_CN_TRA     2250
#define IDS_CARPLAY_MAIN_PROMPT_CN_TRA  2251
#define IDS_SETTING_DISPLAY_CN_TRA      2252
#define IDS_SETTING_LED_RED_CN_TRA      2253
#define IDS_SETTING_LED_GREEN_CN_TRA    2254
#define IDS_SETTING_LED_BLUE_CN_TRA     2255
#define IDS_SETTING_LCD_GAMMA_CN_TRA    2256
#define IDS_SETTING_BLUR_EFFECT_CN_TRA  2257
#define IDS_SETTING_LED_BRIGHTNESS_CN_TRA 2258
#define IDS_RESET_DEFAULT_CN_TRA        2259
#define IDS_ACTIVATE_PROMPT_0_CN_TRA    2260
#define IDS_SETTING_VOL_NAVI_SPEECH_CN_TRA 2261
#define IDS_SETTING_DRIVE_TYPE_CN_TRA   2262
#define IDS_SETTING_DRIVE_LEFT_CN_TRA   2263
#define IDS_SETTING_DRIVE_RIGHT_CN_TRA  2264
#define IDS_SETTING_BT_RINGTONE_CN_TRA  2265
#define IDS_SETTING_ADVANCED_CN_TRA     2266
#define IDS_PHONELINK_CONNECT_FAILED_CN_TRA 2267
#define IDS_SETTING_TIMEZONE_CN_TRA     2268
#define IDS_SETTING_BT_AUTO_CONNECT_CN_TRA 2269
#define IDS_SETTING_PANEL_LIGHT_CN_TRA  2270
#define IDS_SETTING_PANEL_LIGHT_DISC_CN_TRA 2271
#define IDS_SETTING_PANEL_LIGHT_COLOR_CN_TRA 2272
#define IDS_SETTING_PANEL_LIGHT_BRIGHTNESS_CN_TRA 2273
#define IDS_DIAL_CHN_TRA                2274
#define IDS_SETTING_KOREA_CN_TRA        2275
#define IDS_SETTING_ADVANCE_CN_TRA      2276
#define IDS_SETTING_STEER_WHEEL_CN_TRA  2277
#define IDS_SETTING_STEER_WHEEL_DESC_CN_TRA 2278
#define IDS_SETTING_STEER_WHEEL_PROMPT_CN_TRA 2279
#define IDS_SETTING_STEER_WHEEL_RECALIBRATE_CN_TRA 2280
#define IDS_IMAGE_UPDATING_CN_TRA       2281
#define IDS_IMAGE_UPDATE_CONFIRM_CN_TRA 2282
#define IDS_RESTART_SYSTEM_CN_TRA       2283
#define IDS_SETTING_RESET_CN_TRA        2284
#define IDS_SETTING_SOUTHAMERICA_CN_TRA 2284
#define IDS_SETTING_HARDWARE_ID_CN_TRA  2285
#define IDS_SETTING_REARVIEW_SETTING_CN_TRA 2286
#define IDS_SETTING_REARVIEW_TITLE_CN_TRA 2287
#define IDS_SETTING_LED_ANIM_EFFECT_CN_TRA 2288
#define IDS_SETTING_ENTER_PASSWORD_CN_TRA 2289
#define IDS_SETTING_SCREEN_BRIGHTNESS_CN_TRA 2290
#define IDS_CONFIRM_DOWNLOAD_PB_CN_TRA  2291
#define IDS_SETTING_TIME_AUTO_ADJUST_DLST_CN_TRA 2292
#define IDS_SETTING_ENABLE_REAR_VOL_CONTROL_CN_TRA 2293
#define IDS_SETTING_STW_CALIBRATE_CN_TRA 2294
#define IDS_AUX_PLAYING_CN_TRA          2295
#define IDS_AUX_TIP2_CN_TRA             2296
#define IDS_CONFIRM_DOWNLOAD_CALLHISTORY_CN_TRA 2297
#define IDS_SETTING_WHEEL_CN_TRA        2298
#define IDS_SETTING_RADIO_RBDS_SWITCH_CN_TRA 2299
#define IDS_SETTING_AUDIO_SUBWOOFER_FREQ_CN_TRA 2300
#define IDS_SETTING_DISPLAY_TITLE_LCD_CN_TRA 2301
#define IDS_BT_PHONEBOOK_SYNC_CN_TRA    2302
#define IDS_BT_PHONEBOOK_BACK_CN_TRA    2303
#define IDS_BT_PHONEBOOK_FIRST_NAME_FIRST_CN_TRA 2304
#define IDS_SETTING_CHARGING_ONLY_CN_TRA 2305
#define IDS_TAIWAN_CN_TRA               2306
#define IDS_SOUTH_AMERICA_CN_TRA        2307
#define IDS_ARABIA_AUSTRALIA_CN_TRA     2308
#define IDS_LATIN_AMERICA_CN_TRA        2309
#define IDS_MIDDLE_EAST_CN_TRA          2310
#define IDS_AUST_CN_TRA                 2311
#define IDS_BRAZIL_CN_TRA               2312
#define IDS_RUSSIA_CN_TRA               2313
#define IDS_SETTING_ANDROID_TYPE_CN_TRA 2314
#define IDS_USB_HUB_UNSUPPORTED_CN_TRA  2315
#define IDS_AUTO_LAUNCH_CN_TRA          2316
#define IDS_DAY_CN_TRA                  2317
#define IDS_NIGHT_CN_TRA                2318
#define IDS_STW_VOL_ADD_CN_TRA          2319
#define IDS_STW_VOL_SUB_CN_TRA          2320
#define IDS_STW_MUTE_CN_TRA             2321
#define IDS_STW_PREVIOUS_CN_TRA         2322
#define IDS_STW_NEXT_CN_TRA             2323
#define IDS_STW_SEEK_CN_TRA             2324
#define IDS_STW_CALL_CN_TRA             2325
#define IDS_STW_HANGUP_CN_TRA           2326
#define IDS_STW_SPEECH_CN_TRA           2327
#define IDS_STW_POWER_CN_TRA            2328
#define IDS_STW_MODE_CN_TRA             2329
#define IDS_STW_NAVI_CN_TRA             2330
#define IDS_STW_UNDEFINE_CN_TRA         2331
#define IDS_STW_ACTIVATED_CN_TRA        2332
#define IDS_AA_NOTE1_CN_TRA             2333
#define IDS_AA_NOTE2_CN_TRA             2334
#define IDS_AA_NOTE3_CN_TRA             2335
#define IDS_MHZ_CN_TRA                  2336
#define IDS_KHZ_CN_TRA                  2337
#define IDS_KEYPAD_CN_TRA         		2338
#define IDS_HANGUP_CN_TRA         		2339
#define IDS_ANSWER_CN_TRA         		2340
#define IDS_PRIVACY_CN_TRA         		2341
#define IDS_HANDS_FREE_CN_TRA         	2342
#define IDS_APP_TITLE_CN_SIN            3001
#define IDC_LIGHTNINGUI_CN_SIN          3002
#define IDS_TITLE_RADIO_CN_SIN          3010
#define IDS_TITLE_BLUETOOTH_CN_SIN      3011
#define IDS_TITLE_MEDIA_CN_SIN          3012
#define IDS_TITLE_PHONELINK_CN_SIN      3013
#define IDS_TITLE_NAVI_CN_SIN           3014
#define IDS_TITLE_TV_CN_SIN             3015
#define IDS_TITLE_MHL_CN_SIN            3016
#define IDS_TITLE_DISK_CN_SIN           3017
#define IDS_TITLE_AUX_CN_SIN            3018
#define IDS_TITLE_IPOD_CN_SIN           3019
#define IDS_TITLE_SETTINGS_CN_SIN       3020
#define IDS_TITLE_VEHICLEINFO_CN_SIN    3021
#define IDS_TITLE_MUSIC_CN_SIN          3022
#define IDS_TITLE_VIDEO_CN_SIN          3023
#define IDS_TITLE_IMAGE_CN_SIN          3024
#define IDS_TITLE_TIME_CN_SIN           3025
#define IDS_TITLE_DATE_CN_SIN           3026
#define IDS_TITLE_USB_CN_SIN            3027
#define IDS_TITLE_SD_CN_SIN             3028
#define IDS_TITLE_CD_CN_SIN             3029
#define IDS_TITLE_DVD_CN_SIN            3030
#define IDS_TITLE_APPS_CN_SIN           3031
#define IDS_UNKNOWN_CN_SIN              3032
#define IDS_SUNDAY_CN_SIN               3033
#define IDS_MONDAY_CN_SIN               3034
#define IDS_TUESDAY_CN_SIN              3035
#define IDS_WEDNESDAY_CN_SIN            3036
#define IDS_THURSDAY_CN_SIN             3037
#define IDS_FRIDAY_CN_SIN               3038
#define IDS_SATURDAY_CN_SIN             3039
#define IDS_JANUARY_CN_SIN              3040
#define IDS_FEBRUARY_CN_SIN             3041
#define IDS_MARCH_CN_SIN                3042
#define IDS_APRIL_CN_SIN                3043
#define IDS_MAY_CN_SIN                  3044
#define IDS_JUNE_CN_SIN                 3045
#define IDS_JULY_CN_SIN                 3046
#define IDS_AUGUST_CN_SIN               3047
#define IDS_SEPTEMBER_CN_SIN            3048
#define IDS_OCTOBER_CN_SIN              3049
#define IDS_NOVEMBER_CN_SIN             3050
#define IDS_DECEMBER_CN_SIN             3051
#define IDS_ON_CN_SIN                   3052
#define IDS_OFF_CN_SIN                  3053
#define IDS_YES_CN_SIN                  3054
#define IDS_NO_CN_SIN                   3055
#define IDS_OK_CN_SIN_CN_SIN            3056
#define IDS_CANCEL_CN_SIN               3057
#define IDS_RESET_CN_SIN                3058
#define IDS_CONFIRM_CN_SIN              3059
#define IDS_CONNECTING_CN_SIN           3060
#define IDS_CONNECTED_CN_SIN            3061
#define IDS_LOADING_CN_SIN              3062
#define IDS_TITLE_REARVIEW_CN_SIN       3063
#define IDS_PARKING_NOTICE_CN_SIN       3064
#define IDS_NO_SIGNAL_CN_SIN            3065
#define IDS_CAN_BELT_CN_SIN             3066
#define IDS_CAN_OUTSIDE_TEMP_CN_SIN     3067
#define IDS_CAN_BATTERY_CN_SIN          3068
#define IDS_CAN_OIL_CN_SIN              3069
#define IDS_CAN_HANDBRAKE_CN_SIN        3070
#define IDS_CAN_TRIP_CN_SIN             3071
#define IDS_CAN_ENGIN_SPEED_CN_SIN      3072
#define IDS_CAN_CLEANINGWATER_CN_SIN    3073
#define IDS_CAN_VELOCITY_CN_SIN         3074
#define IDS_CAN_AIR_CN_SIN              3075
#define IDS_CAN_BODY_CN_SIN             3076
#define IDS_CAN_RADAR_CN_SIN            3077
#define IDS_CAN_HANDBRAKE_UNRELEASED_CN_SIN 3078
#define IDS_SETTINGS_HIGH_CN_SIN        3079
#define IDS_SETTINGS_LOW_CN_SIN         3080
#define IDS_SETTINGS_NORMAL_CN_SIN      3081
#define IDS_PHONELINK_MAIN_PROMPT_CN_SIN 3082
#define IDS_PHONELINK_INSTALLING_CN_SIN 3083
#define IDS_PHONELINK_INSTALL_OK_CN_SIN 3084
#define IDS_PHONELINK_NO_USB_DEBUG_CN_SIN 3085
#define IDS_PHONELINK_CONNECTING_CN_SIN 3086
#define IDS_MHL_MAIN_PROMPT_CN_SIN      3087
#define IDS_MHL_CONNECTING_CN_SIN       3088
#define IDS_MHL_CONNECTED_CN_SIN        3089
#define IDS_MHL_WAITING_CN_SIN          3090
#define IDS_TITLE_PHONE_CN_SIN          3091
#define IDS_DEVICE_REMOVE_CN_SIN        3092
#define IDS_DEVICE_INSERT_CN_SIN        3093
#define IDS_DEVICE_RESIDENTFLASH_CN_SIN 3094
#define IDS_DEVICE_IPOD_CN_SIN          3095
#define IDS_DEVICE_USB_CN_SIN           3096
#define IDS_DEVICE_BT_CN_SIN            3097
#define IDS_DEVICE_SD_CN_SIN            3098
#define IDS_DEVICE_CD_CN_SIN            3099
#define IDS_DEVICE_LINEIN_FRONT_CN_SIN  3100
#define IDS_DEVICE_LINEIN_REAR_CN_SIN   3101
#define IDS_NO_MEDIA_FILES_CN_SIN       3102
#define IDS_WARNING_CN_SIN              3103
#define IDS_CANNOT_WATCH_VIDEO_CN_SIN   3104
#define IDS_BROWSING_ACTIVE_CN_SIN      3105
#define IDS_LIBRARY_MENU_ALBUMS_CN_SIN  3106
#define IDS_LIBRARY_MENU_ARTISTS_CN_SIN 3107
#define IDS_LIBRARY_MENU_COMPOSERS_CN_SIN 3108
#define IDS_LIBRARY_MENU_GENRES_CN_SIN  3109
#define IDS_LIBRARY_MENU_EXPLORE_CN_SIN 3110
#define IDS_LIBRARY_MENU_TRACKS_CN_SIN  3111
#define IDS_LIBRARY_MENU_PLAYLISTS_CN_SIN 3112
#define IDS_LIBRARY_MENU_PODCASTS_CN_SIN 3113
#define IDS_LIBRARY_MENU_EPISODES_CN_SIN 3114
#define IDS_LIBRARY_MENU_AUDIOBOOKS_CN_SIN 3115
#define IDS_NOWPLAYING_PLAYING_CN_SIN   3116
#define IDS_NOWPLAYING_INVALIDMEDIA_CN_SIN 3117
#define IDS_TITLE_HOME_CN_SIN           3118
#define IDS_TITLE_NOWPLAYING_CN_SIN     3119
#define IDS_SEARCH_CN_SIN               3120
#define IDS_LOCATION_MOBILE_CN_SIN      3121
#define IDS_LOCATION_WORK_CN_SIN        3122
#define IDS_LOCATION_HOME_CN_SIN        3123
#define IDS_DISCONNECTING_CN_SIN        3124
#define IDS_DISCONNECTED_CN_SIN         3125
#define IDS_CALL_CN_SIN                 3126
#define IDS_DISCONNECT_DEVICE_CN_SIN    3127
#define IDS_CS_HOLD_CN_SIN              3128
#define IDS_CS_DIALING_CN_SIN           3129
#define IDS_CS_INCOMING_CALL_CN_SIN     3130
#define IDS_CS_WAITING_CALL_CN_SIN      3131
#define IDS_DOWNLOADING_CN_SIN          3132
#define IDS_CAN_BELT_UNBUCKLED_CN_SIN   3133
#define IDS_STEREO_CN_SIN               3134
#define IDS_MONO_CN_SIN                 3135
#define IDS_LOC_CN_SIN                  3136
#define IDS_FAVORITE_CN_SIN             3137
#define IDS_PAIRED_CN_SIN               3138
#define IDS_DOWNLOAD_CN_SIN             3139
#define IDS_DEVICE_MGR_CN_SIN           3140
#define IDS_NO_DEVICE_PAIRED_CN_SIN     3141
#define IDS_PHONECORE_FINDME_NOTE_CN_SIN 3142
#define IDS_NO_DEVICE_FOUND_CN_SIN      3143
#define IDS_SETTING_GENERAL_CN_SIN      3144
#define IDS_SETTING_AUDIO_CN_SIN        3145
#define IDS_SETTING_BLUETOOTH_CN_SIN    3146
#define IDS_SETTING_RADIO_CN_SIN        3147
#define IDS_SETTING_ABOUT_CN_SIN        3148
#define IDS_SETTING_HANDBRAKE_TEST_CN_SIN 3149
#define IDS_SETTING_REVERSE_POLAR_CN_SIN 3150
#define IDS_SETTING_LAMP_CONTROL_CN_SIN 3151
#define IDS_SETTING_DATE_AND_TIME_CN_SIN 3152
#define IDS_SETTING_DATE_CN_SIN         3153
#define IDS_SETTING_TIME_CN_SIN         3154
#define IDS_SETTING_24H_MODE_CN_SIN     3155
#define IDS_SETTING_TIME_AUTO_ADJUST_CN_SIN 3156
#define IDS_SETTING_NAVIGATION_CN_SIN   3157
#define IDS_SETTING_NAVI_LAUNCH_LOCATION_CN_SIN 3158
#define IDS_SETTING_NAVI_SPEECH_CN_SIN  3159
#define IDS_SETTING_LANGUAGE_CN_SIN     3160
#define IDS_SETTING_LANG_CHN_SIM_CN_SIN 3161
#define IDS_SETTING_LANG_CHN_TRA_CN_SIN 3162
#define IDS_SETTING_LANG_ENGLISH_CN_SIN 3163
#define IDS_SETTING_NAVI_SPEECH_ALWAYS_CN_SIN 3164
#define IDS_SETTING_NAVI_SPEECH_CLOSED_CN_SIN 3165
#define IDS_SETTING_NAVI_SPEECH_MAP_CN_SIN 3166
#define IDS_SETTING_MUTE_CN_SIN         3167
#define IDS_SETTING_LOUDNESS_CN_SIN     3168
#define IDS_SETTING_VOLUME_VELOCITY_ADJUST_CN_SIN 3169
#define IDS_SETTING_AUDIO_EFFECT_CN_SIN 3170
#define IDS_SETTING_CLASSIC_CN_SIN      3171
#define IDS_SETTING_POP_CN_SIN          3172
#define IDS_SETTING_ROCK_CN_SIN         3173
#define IDS_SETTING_JAZZ_CN_SIN         3174
#define IDS_SETTING_USER_CN_SIN         3175
#define IDS_SETTING_EQ_CN_SIN           3176
#define IDS_SETTING_BAL_FAD_CN_SIN      3177
#define IDS_SETTING_LOW_CN_SIN          3178
#define IDS_SETTING_MID_CN_SIN          3179
#define IDS_SETTING_HIGH_CN_SIN         3180
#define IDS_SETTING_BT_POWER_CN_SIN     3181
#define IDS_SETTING_BT_DEVICE_NAME_CN_SIN 3182
#define IDS_SETTING_BT_PAIR_PIN_CN_SIN  3183
#define IDS_SETTING_BT_AUTO_ANSWER_CN_SIN 3184
#define IDS_SETTING_BT_AUTO_DOWNLOAD_PB_CN_SIN 3185
#define IDS_SETTING_RADIO_SEEK_QUALITY_CN_SIN 3186
#define IDS_SETTING_RADIO_FM_CN_SIN     3187
#define IDS_SETTING_RADIO_AM_CN_SIN     3188
#define IDS_SETTING_RADIO_RESET_SEEK_QUALITY_CN_SIN 3189
#define IDS_SETTING_RADIO_REGION_CN_SIN 3190
#define IDS_SETTING_EUROPE_CN_SIN       3191
#define IDS_SETTING_USA_CN_SIN          3192
#define IDS_SETTING_EASTERN_EUROPE_CN_SIN 3193
#define IDS_SETTING_JAPAN_CN_SIN        3194
#define IDS_SETTING_RADIO_RDS_SWITCH_CN_SIN 3195
#define IDS_SETTING_OS_VERSION_CN_SIN   3196
#define IDS_SETTING_SOFTWARE_VERSION_CN_SIN 3197
#define IDS_SETTING_MCU_VERSION_CN_SIN  3198
#define IDS_SETTING_HARDWARE_VERSION_CN_SIN 3199
#define IDS_VEHICLE_DRIVE_CN_SIN        3200
#define IDS_VEHICLE_AC_CN_SIN           3201
#define IDS_VEHICLE_BODY_CN_SIN         3202
#define IDS_VEHICLE_RADAR_CN_SIN        3203
#define IDS_NO_MEDIA_DEVICE_CN_SIN      3204
#define IDS_INPUT_NEW_DEVICE_NAME_CN_SIN 3205
#define IDS_INPUT_NEW_PAIR_PIN_CN_SIN   3206
#define IDS_CALL_HISTORY_CN_SIN         3207
#define IDS_CONTACT_CN_SIN              3208
#define IDS_SEARCHING_CN_SIN            3209
#define IDS_CS_CONNECTED_CN_SIN         3210
#define IDS_NOT_CONNECTED_CN_SIN        3211
#define IDS_BT_CONNECT_SETTING_CN_SIN   3212
#define IDS_BT_PAIRING_CN_SIN           3213
#define IDS_BT_DEVICE_PAIRED_CN_SIN     3214
#define IDS_RESET_TO_TAKE_EFFECT_CN_SIN 3215
#define IDS_SETTING_IDLE_SCREEN_CN_SIN  3216
#define IDS_CLOCK_ANALOG_CN_SIN         3217
#define IDS_CLOCK_DIGITAL_CN_SIN        3218
#define IDS_NONE_CN_SIN                 3219
#define IDS_MEDIA_BROWSE_FOLDER_CN_SIN  3220
#define IDS_MEDIA_BROWSE_TRACK_CN_SIN   3221
#define IDS_MEDIA_BROWSE_PARENT_FOLDER_CN_SIN 3222
#define IDS_SETTING_CAMERA_TYPE_CN_SIN  3223
#define IDS_UPDATE_CN_SIN               3224
#define IDS_MCU_UPDATE_CONFIRM_CN_SIN   3225
#define IDS_MCU_UPDATE_PROMPT_CN_SIN    3226
#define IDS_MCU_UPDATING_CN_SIN         3227
#define IDS_MCU_UPDATING_ALERT_CN_SIN   3228
#define IDS_MCU_UPDATING_INVALID_FILE_CN_SIN 3229
#define IDS_MCU_UPDATE_SUCCEED_CN_SIN   3230
#define IDS_MCU_UPDATE_FAILED_CN_SIN    3231
#define IDS_SETTING_UI_CN_SIN           3232
#define IDS_SETTING_UI_SKIN_CN_SIN      3233
#define IDS_SETTING_SUBWOOFER_CN_SIN    3234
#define IDS_SETTING_UI_BACKGROUND_CN_SIN 3235
#define IDS_RETURN_CN_SIN               3236
#define IDS_BT_STREAMING_AUDIO_CN_SIN   3237
#define IDS_BT_STREAMING_AUDIO_TERMINATE_CN_SIN 3238
#define IDS_STRANGER_CN_SIN             3239
#define IDS_SETTING_UI_FACTORY_CN_SIN   3240
#define IDS_SETTING_UI_RESTORE_FACTORY_SETTINGS_CN_SIN 3241
#define IDS_SETTING_UI_DEFAULT_CN_SIN   3242
#define IDS_SETTING_VOLUME_CN_SIN       3243
#define IDS_UPDATE_PROMPT_0_CN_SIN      3244
#define IDS_UPDATE_PROMPT_1_CN_SIN      3245
#define IDS_UPDATE_PROMPT_2_CN_SIN      3246
#define IDS_UPDATE_PROMPT_3_CN_SIN      3247
#define IDS_NO_LISTITEM_CN_SIN          3248
#define IDS_SETTING_UI_BACK_LUMIN_CN_SIN 3249
#define IDS_SETTING_KEY_BEEP_CN_SIN     3250
#define IDS_CARPLAY_MAIN_PROMPT_CN_SIN  3251
#define IDS_SETTING_DISPLAY_CN_SIN      3252
#define IDS_SETTING_LED_RED_CN_SIN      3253
#define IDS_SETTING_LED_GREEN_CN_SIN    3254
#define IDS_SETTING_LED_BLUE_CN_SIN     3255
#define IDS_SETTING_LCD_GAMMA_CN_SIN    3256
#define IDS_SETTING_BLUR_EFFECT_CN_SIN  3257
#define IDS_SETTING_LED_BRIGHTNESS_CN_SIN 3258
#define IDS_RESET_DEFAULT_CN_SIN        3259
#define IDS_ACTIVATE_PROMPT_0_CN_SIN    3260
#define IDS_SETTING_VOL_NAVI_SPEECH_CN_SIN 3261
#define IDS_SETTING_DRIVE_TYPE_CN_SIN   3262
#define IDS_SETTING_DRIVE_LEFT_CN_SIN   3263
#define IDS_SETTING_DRIVE_RIGHT_CN_SIN  3264
#define IDS_SETTING_BT_RINGTONE_CN_SIN  3265
#define IDS_SETTING_ADVANCED_CN_SIN     3266
#define IDS_PHONELINK_CONNECT_FAILED_CN_SIN 3267
#define IDS_SETTING_TIMEZONE_CN_SIN     3268
#define IDS_SETTING_BT_AUTO_CONNECT_CN_SIN 3269
#define IDS_SETTING_PANEL_LIGHT_CN_SIN  3270
#define IDS_SETTING_PANEL_LIGHT_DISC_CN_SIN 3271
#define IDS_SETTING_PANEL_LIGHT_COLOR_CN_SIN 3272
#define IDS_SETTING_PANEL_LIGHT_BRIGHTNESS_CN_SIN 3273
#define IDS_DIAL_CHN_SIN                3274
#define IDS_SETTING_KOREA_CN_SIN        3275
#define IDS_SETTING_ADVANCE_CN_SIN      3276
#define IDS_SETTING_STEER_WHEEL_CN_SIN  3277
#define IDS_SETTING_STEER_WHEEL_DESC_CN_SIN 3278
#define IDS_SETTING_STEER_WHEEL_PROMPT_CN_SIN 3279
#define IDS_SETTING_STEER_WHEEL_RECALIBRATE_CN_SIN 3280
#define IDS_IMAGE_UPDATING_CN_SIN       3281
#define IDS_IMAGE_UPDATE_CONFIRM_CN_SIN 3282
#define IDS_RESTART_SYSTEM_CN_SIN       3283
#define IDS_SETTING_RESET_CN_SIN        3284
#define IDS_SETTING_SOUTHAMERICA_CN_SIN 3284
#define IDS_SETTING_HARDWARE_ID_CN_SIN  3285
#define IDS_SETTING_REARVIEW_SETTING_CN_SIN 3286
#define IDS_SETTING_REARVIEW_TITLE_CN_SIN 3287
#define IDS_SETTING_LED_ANIM_EFFECT_CN_SIN 3288
#define IDS_SETTING_ENTER_PASSWORD_CN_SIN 3289
#define IDS_SETTING_SCREEN_BRIGHTNESS_CN_SIN 3290
#define IDS_CONFIRM_DOWNLOAD_PB_CN_SIN  3291
#define IDS_SETTING_TIME_AUTO_ADJUST_DLST_CN_SIN 3292
#define IDS_SETTING_ENABLE_REAR_VOL_CONTROL_CN_SIN 3293
#define IDS_SETTING_STW_CALIBRATE_CN_SIN 3294
#define IDS_AUX_PLAYING_CN_SIN          3295
#define IDS_AUX_TIP2_CN_SIN             3296
#define IDS_CONFIRM_DOWNLOAD_CALLHISTORY_CN_SIN 3297
#define IDS_SETTING_WHEEL_CN_SIN        3298
#define IDS_SETTING_RADIO_RBDS_SWITCH_CN_SIN 3299
#define IDS_SETTING_AUDIO_SUBWOOFER_FREQ_CN_SIN 3300
#define IDS_SETTING_DISPLAY_TITLE_LCD_CN_SIN 3301
#define IDS_BT_PHONEBOOK_SYNC_CN_SIN    3302
#define IDS_BT_PHONEBOOK_BACK_CN_SIN    3303
#define IDS_BT_PHONEBOOK_FIRST_NAME_FIRST_CN_SIN 3304
#define IDS_SETTING_CHARGING_ONLY_CN_SIN 3305
#define IDS_TAIWAN_CN_SIN               3306
#define IDS_SOUTH_AMERICA_CN_SIN        3307
#define IDS_ARABIA_AUSTRALIA_CN_SIN     3308
#define IDS_LATIN_AMERICA_CN_SIN        3309
#define IDS_MIDDLE_EAST_CN_SIN          3310
#define IDS_AUST_CN_SIN                 3311
#define IDS_BRAZIL_CN_SIN               3312
#define IDS_RUSSIA_CN_SIN               3313
#define IDS_SETTING_ANDROID_TYPE_CN_SIN 3314
#define IDS_USB_HUB_UNSUPPORTED_CN_SIN  3315
#define IDS_AUTO_LAUNCH_CN_SIN          3316
#define IDS_DAY_CN_SIN                  3317
#define IDS_NIGHT_CN_SIN                3318
#define IDS_STW_VOL_ADD_CN_SIN          3319
#define IDS_STW_VOL_SUB_CN_SIN          3320
#define IDS_STW_MUTE_CN_SIN             3321
#define IDS_STW_PREVIOUS_CN_SIN         3322
#define IDS_STW_NEXT_CN_SIN             3323
#define IDS_STW_SEEK_CN_SIN             3324
#define IDS_STW_CALL_CN_SIN             3325
#define IDS_STW_HANGUP_CN_SIN           3326
#define IDS_STW_SPEECH_CN_SIN           3327
#define IDS_STW_POWER_CN_SIN            3328
#define IDS_STW_MODE_CN_SIN             3329
#define IDS_STW_NAVI_CN_SIN             3330
#define IDS_STW_UNDEFINE_CN_SIN         3331
#define IDS_STW_ACTIVATED_CN_SIN        3332
#define IDS_AA_NOTE1_CN_SIN             3333
#define IDS_AA_NOTE2_CN_SIN             3334
#define IDS_AA_NOTE3_CN_SIN             3335
#define IDS_MHZ_CN_SIN                  3336
#define IDS_KHZ_CN_SIN                  3337
#define IDS_KEYPAD_CN_SIN         		3338
#define IDS_HANGUP_CN_SIN         		3339
#define IDS_ANSWER_CN_SIN         		3340
#define IDS_PRIVACY_CN_SIN         		3341
#define IDS_HANDS_FREE_CN_SIN         	3342

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        253
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
