#ifndef __CUSTOMER_H__
#define __CUSTOMER_H__

#include "feature.h"

#define	Stringify( X )				# X
#define	StringifyExpansion( X )		Stringify( X )

#define CUSTOMER_ID			 CUSTOMER_U702P_DEFAULT

#include StringifyExpansion(customer/CUSTOMER_ID.h)

#define CUSTOMER_DEFAULT		0
#define CUSTOMER_CVTE			1
#define CUSTOMER_ICARTECH		2
#define CUSTOMER_ENTERFRONT	    3
#define CUSTOMER_PROLOGY		4
#define CUSTOMER_MAPMYINDIA	    5
#define CUSTOMER_ALDINET		6
#define CUSTOMER_SOUNDEXPRESS   7
#define CUSTOMER_MINSHENG       8
#define CUSTOMER_ERKE           9
#define CUSTOMER_DAIICHI        10
#define CUSTOMER_BOSSAUDIO      11
#define CUSTOMER_AVT            12
#define CUSTOMER_VOXX           13
#define CUSTOMER_ACTION         14
#define CUSTOMER_ALPHATRONICS   15
#define CUSTOMER_AUTONET        16
#define CUSTOMER_PHONOCAR       17
#define CUSTOMER_NEMESIS        18
#define CUSTOMER_CALIBER        19
#define CUSTOMER_PST            20
#define CUSTOMER_TAWANG         21
#define CUSTOMER_AXION          22
#define CUSTOMER_EPSILON        23
#define CUSTOMER_ITAMCO         24
#define CUSTOMER_FURRION		25
#define CUSTOMER_SMARTNAVI		26
#define CUSTOMER_CAR_VISION		27
#define CUSTOMER_ACR			28
#define CUSTOMER_CARMAX			29
#define CUSTOMER_DAIICHI_FIAT_DUCATO	30
#define CUSTOMER_RAMBO			31
#define CUSTOMER_DAIICHI_FIAT_DOBLO	32
#define CUSTOMER_DAIICHI_MITSUBISHI_L200 33
#define CUSTOMER_AUTOVISION		34
#define CUSTOMER_DAIICHI_FIAT_FULLBACK	35
#define CUSTOMER_U705PM_DEFAULT	36
#define CUSTOMER_U702P_DEFAULT	37
#define CUSTOMER_U703PT_DEFAULT 38
#define CUSTOMER_U621P_DEFAULT	39
#define CUSTOMER_T7				40
#define CUSTOMER_T8				41
#define CUSTOMER_FSK			42
#define CUSTOMER_ALLVISION		43
#define CUSTOMER_PLANETAUDIO	44
#define CUSTOMER_NSA			45
#define CUSTOMER_CVTE_CERTIFICATION			46
#define CUSTOMER_DS702P_ITAMCO	47
#define CUSTOMER_MALAYSIA_KIA	48
#define CUSTOMER_DAIICHI_KIA_IRAN 49
#define CUSTOMER_PROUD			50
#define CUSTOMER_DS701P_DAIICHI_FIAT_DOBLO 51
#define CUSTOMER_BONANZA		52
#define CUSTOMER_BLACKWOOD		53
#define CUSTOMER_AYONZ			54
#define CUSTOMER_CATHY			55
#define CUSTOMER_INCAR			56
#define CUSTOMER_MISION			57
#define CUSTOMER_SOUNDEXPRESS_BOA	58
#define CUSTOMER_PSS				59
#define CUSTOMER_BAWANI			60
#define CUSTOMER_PROUD_MGTS		61
#define CUSTOMER_PHONOCAR_U701P	62
#define CUSTOMER_FAAFTECH_U702P	63
#define CUSTOMER_BONANZA_U701P	64
#define CUSTOMER_U703PT_7738	65
#define CUSTOMER_PROUD_LOGIGO	66
#define CUSTOMER_FC707P			67
#define CUSTOMER_PROUD_U702P_NEWUI	68
#define CUSTOMER_MISION_U621P		69

#include "Model.h"
		
#include "feature_default.h"

#include "feature_check.h"

#endif
