#ifndef __MODEL_H__
#define __MODEL_H__

#if (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U701P_C)
	
	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U701P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U701P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U701P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U701P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U701P
	
#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U701P_DE)
	
	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U701P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U701P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U701P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U701P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U701P
	
#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U701P_E_ASP)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U701P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U701P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U701P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_FM1388_AIC3254_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U701P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U701P

	//audio wave ID settings:
	#define CVTE_DEF_AUDIO_DEVICE_ID_INPUT	1

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U621P_C)
	
	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U621P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U621P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U621P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U621P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U621P
	
#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U621P_DE)
	
	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U621P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U621P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U621P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U621P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U621P	

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U621P_E_ASP)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U621P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U621P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U621P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_FM1388_AIC3254_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U621P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U621P	

	//audio wave ID settings:
	#define CVTE_DEF_AUDIO_DEVICE_ID_INPUT	1

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U702P)
	
	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U702P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U702P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U702P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U702P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U702P	

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U702P_ASP)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U702P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U702P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U702P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_FM1388_AIC3254_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U702P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U702P	
	
	//audio wave ID settings:
	#define CVTE_DEF_AUDIO_DEVICE_ID_INPUT	1

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U703PT)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U703PT
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U703PT
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U703PT
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U703PT
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U703PT	
	
#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U703PT_ASP)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U703PT
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U703PT
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U703PT
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_FM1388_AIC3254_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U703PT
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U703PT	

	//audio wave ID settings:
	#define CVTE_DEF_AUDIO_DEVICE_ID_INPUT	1

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U705PM)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U705PM
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U705PM
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U705PM
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U705PM
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U705PM

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_DS702P)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_DS702P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_DS702P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_DS702P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_DS702P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_DS702P	

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_DS702P_ASP)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_DS702P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_DS702P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_DS702P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_FM1388_AIC3254_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_DS702P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_DS702P

	//audio wave ID settings:
	#define CVTE_DEF_AUDIO_DEVICE_ID_INPUT	1

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_DS701P)
	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_DS701P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_DS701P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_DS701P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_DS701P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_DS701P	

#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_DS701P_ASP)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_DS701P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_DS701P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_DS701P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_FM1388_AIC3254_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_DS701P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_DS701P

	//audio wave ID settings:
	#define CVTE_DEF_AUDIO_DEVICE_ID_INPUT	1
#elif (CVTE_MODEL_TYPE == CVTE_MODEL_TYPE_U703PT_DSP_AK7738)

	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U703PT
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U703PT
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U703PT
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_AK7738
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U703PT
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U703PT	

	//audio wave ID settings:
	#define CVTE_DEF_AUDIO_DEVICE_ID_INPUT	1
#else
	
	//Display type
	#define CVTE_DEF_DISPLAY_TYPE 			CVTE_DISPLAY_TYPE_U701P
	//Led type
	#define CVTE_DEF_LED_TYPE 				CVTE_LED_TYPE_U701P
	//Touch type
	#define CVTE_DEF_TOUCH_TYPE 			CVTE_TOUCH_TYPE_U701P
	//Audio type
	#define CVTE_DEF_AUDIO_TYPE 			CVTE_AUDIO_TYPE_ST7418
	//Carplay Screen physical width
	#define CVTE_DEF_SCREEN_PHYSICALWIDTH	CVTE_SCREEN_PHYSICALWIDTH_U701P
	//Carplay Screen physical height
	#define CVTE_DEF_SCREEN_PHYSICALHEIGHT	CVTE_SCREEN_PHYSICALHEIGHT_U701P	
	
#endif

#endif