/* SVN $Id: //SoCSW/connectivity/UniFi/CE6/Rel/Built/RoadiHub_7.8.2_P4/WDK/Wifi/SDK/INC/windot11_wfd.h#1 $ */
/*++

    Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    windot11.h

Abstract:

    Definitions for native 802.11 miniport driver specifications.

--*/
//-----------------------------------------------------------------------------
/// \brief      Wi-Fi Direct OIDs  from the Windows 8 DDK
//-----------------------------------------------------------------------------
/// \file

#ifndef __WINDOT11_WFD_H__
#define __WINDOT11_WFD_H__

#pragma once

#include <bldver.h>

#pragma warning(push)
#pragma warning(disable:4201)
#pragma warning(disable:4127)
#include <ndis.h>
#pragma warning(pop)

#if (CE_MAJOR_VER < 7 )
#include <windot11_ce6.h>
#else
#include <windot11.h>
#endif 

#ifndef _Field_range_
#define _Field_range_(l,h)
#endif

/******************************************************************************************\

OID                                             DEVICE      GROUP OWNER     CLIENT
                                                INIT        INIT    OP      INIT    OP
OID_DOT11_WFD_DEVICE_CAPABILITY                 S           S       S       S       S
OID_DOT11_WFD_GROUP_OWNER_CAPABILITY            -           S       S       -       -
OID_DOT11_WFD_DEVICE_INFO                       S           S       -       S       -
OID_DOT11_WFD_DEVICE_LISTEN_CHANNEL             S,Q         -       -       -       -
OID_DOT11_WFD_SECONDARY_DEVICE_TYPE_LIST        S           S       S       S       S
OID_DOT11_WFD_ADDITIONAL_IE                     S           S       S       S       S
OID_DOT11_WFD_DISCOVER_REQUEST                  S           -       -       -       -
OID_DOT11_WFD_STOP_DISCOVERY                    S           -       -       -       -
OID_DOT11_WFD_ENUM_DEVICE_LIST                  Q           -       -       -       -
OID_DOT11_WFD_LISTEN_STATE_DISCOVERABILITY      S,Q         -       -       -       -
OID_DOT11_WFD_FLUSH_DEVICE_LIST                 S           -       -       -       -
OID_DOT11_WFD_GET_DIALOG_TOKEN                  Q           -       -       -       -
OID_DOT11_WFD_SEND_GO_NEGOTIATION_REQUEST       S           -       -       -       -
OID_DOT11_WFD_SEND_GO_NEGOTIATION_RESPONSE      D           -       -       -       -
OID_DOT11_WFD_SEND_GO_NEGOTIATION_CONFIRMATION  D           -       -       -       -
OID_DOT11_WFD_SEND_INVITATION_REQUEST           S           -       -       -       -
OID_DOT11_WFD_SEND_INVITATION_RESPONSE          D           -       -       -       -
OID_DOT11_WFD_SEND_PROVISION_DISCOVERY_REQUEST  S           -       -       -       -
OID_DOT11_WFD_SEND_PROVISION_DISCOVERY_RESPONSE D           -       -       -       -
OID_DOT11_WFD_DESIRED_GROUP_ID                  -           S       -       S       -
OID_DOT11_WFD_START_GO_REQUEST                  -           S       -       -       -
OID_DOT11_WFD_CONNECT_TO_GROUP_REQUEST          -           -       -       S       -
OID_DOT11_WFD_DISCONNECT_FROM_GROUP_REQUEST     -           -       -       -       S
OID_DOT11_WFD_GROUP_START_PARAMETERS            -           S       -       -       -
OID_DOT11_WFD_GROUP_JOIN_PARAMETERS             -           -       -       S       -

\******************************************************************************************/

#define NDIS_STATUS_DOT11_WFD_DISCOVER_COMPLETE                             ((NDIS_STATUS)0x40030013L)
#define NDIS_STATUS_DOT11_WFD_GO_NEGOTIATION_REQUEST_SEND_COMPLETE          ((NDIS_STATUS)0x40030014L)
#define NDIS_STATUS_DOT11_WFD_RECEIVED_GO_NEGOTIATION_REQUEST               ((NDIS_STATUS)0x40030015L)
#define NDIS_STATUS_DOT11_WFD_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE         ((NDIS_STATUS)0x40030016L)
#define NDIS_STATUS_DOT11_WFD_RECEIVED_GO_NEGOTIATION_RESPONSE              ((NDIS_STATUS)0x40030017L)
#define NDIS_STATUS_DOT11_WFD_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE     ((NDIS_STATUS)0x40030018L)
#define NDIS_STATUS_DOT11_WFD_RECEIVED_GO_NEGOTIATION_CONFIRMATION          ((NDIS_STATUS)0x40030019L)
#define NDIS_STATUS_DOT11_WFD_INVITATION_REQUEST_SEND_COMPLETE              ((NDIS_STATUS)0x4003001AL)
#define NDIS_STATUS_DOT11_WFD_RECEIVED_INVITATION_REQUEST                   ((NDIS_STATUS)0x4003001BL)
#define NDIS_STATUS_DOT11_WFD_INVITATION_RESPONSE_SEND_COMPLETE             ((NDIS_STATUS)0x4003001CL)
#define NDIS_STATUS_DOT11_WFD_RECEIVED_INVITATION_RESPONSE                  ((NDIS_STATUS)0x4003001DL)
#define NDIS_STATUS_DOT11_WFD_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE     ((NDIS_STATUS)0x4003001EL)
#define NDIS_STATUS_DOT11_WFD_RECEIVED_PROVISION_DISCOVERY_REQUEST          ((NDIS_STATUS)0x4003001FL)
#define NDIS_STATUS_DOT11_WFD_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE    ((NDIS_STATUS)0x40030020L)
#define NDIS_STATUS_DOT11_WFD_RECEIVED_PROVISION_DISCOVERY_RESPONSE         ((NDIS_STATUS)0x40030021L)
#define NDIS_STATUS_DOT11_WFD_GROUP_OPERATING_CHANNEL                       ((NDIS_STATUS)0x40030022L)


typedef UCHAR DOT11_DIALOG_TOKEN;
typedef UCHAR DOT11_WFD_STATUS_CODE;
typedef UCHAR DOT11_WFD_MINOR_REASON_CODE;

#define DOT11_OPERATION_MODE_WFD_DEVICE         0x00000010
#define DOT11_OPERATION_MODE_WFD_GROUP_OWNER    0x00000020
#define DOT11_OPERATION_MODE_WFD_CLIENT         0x00000040

#define DOT11_INCOMING_ASSOC_DECISION_REVISION_2 2
    
    typedef
    struct _DOT11_INCOMING_ASSOC_DECISION_V2
    {
        NDIS_OBJECT_HEADER      Header;
        DOT11_MAC_ADDRESS       PeerMacAddr;
        BOOLEAN                 bAccept;
        USHORT                  usReasonCode;
        ULONG                   uAssocResponseIEsOffset;
        ULONG                   uAssocResponseIEsLength;
        DOT11_WFD_STATUS_CODE   WFDStatus;
    }
    DOT11_INCOMING_ASSOC_DECISION_V2, *PDOT11_INCOMING_ASSOC_DECISION_V2;

#define DOT11_SIZEOF_INCOMING_ASSOC_DECISION_REVISION_2 sizeof(DOT11_INCOMING_ASSOC_DECISION_V2)


#define DOT11_VWIFI_COMBINATION_REVISION_3     3
    typedef 
    struct _DOT11_VWIFI_COMBINATION_V3
    {
        NDIS_OBJECT_HEADER Header;
        ULONG uNumInfrastructure;
        ULONG uNumAdhoc;
        ULONG uNumSoftAP;
        ULONG uNumVirtualStation;
        ULONG uNumWFDGroup;        
    } 
    DOT11_VWIFI_COMBINATION_V3, * PDOT11_VWIFI_COMBINATION_V3;
    
#define DOT11_SIZEOF_VWIFI_COMBINATION_REVISION_3   sizeof(DOT11_VWIFI_COMBINATION_V3)


#define DOT11_WFD_ATTRIBUTES_REVISION_1         1

    typedef 
    struct _DOT11_WFD_ATTRIBUTES
    {
        NDIS_OBJECT_HEADER Header;
        ULONG uNumConcurrentGORole;
        ULONG uNumConcurrentClientRole;
        ULONG WPSVersionsSupported;

        // Device Capabilities
        BOOLEAN bServiceDiscoverySupported;
        BOOLEAN bClientDiscoverabilitySupported;
        BOOLEAN bInfrastructureManagementSupported;

        ULONG uMaxSecondaryDeviceTypeListSize;
        
        DOT11_MAC_ADDRESS DeviceAddress;
        ULONG uInterfaceAddressListCount;    
        PDOT11_MAC_ADDRESS pInterfaceAddressList;
        
        ULONG uNumSupportedCountryOrRegionStrings;
        #ifdef __midl
        [size_is(uNumSupportedCountryOrRegionStrings)]
        #endif    
        PDOT11_COUNTRY_OR_REGION_STRING pSupportedCountryOrRegionStrings;

        // Device Functionality
        ULONG uDiscoveryFilterListSize;

        // GO Capabilities
        ULONG uGORoleClientTableSize;
        
        // Client Capabilities
    }DOT11_WFD_ATTRIBUTES, *PDOT11_WFD_ATTRIBUTES;

#define DOT11_SIZEOF_WFD_ATTRIBUTES_REVISION_1   sizeof(DOT11_WFD_ATTRIBUTES)


// Common WFD data types
typedef UCHAR DOT11_WFD_GROUP_CAPABILITY;

// WFD Status Code
#define DOT11_WFD_STATUS_SUCCESS                                                0
#define DOT11_WFD_STATUS_FAILED_INFORMATION_IS_UNAVAILABLE                      1
#define DOT11_WFD_STATUS_FAILED_INCOMPATIBLE_PARAMETERS                         2
#define DOT11_WFD_STATUS_FAILED_LIMIT_REACHED                                   3
#define DOT11_WFD_STATUS_FAILED_INVALID_PARAMETERS                              4
#define DOT11_WFD_STATUS_FAILED_UNABLE_TO_ACCOMODATE_REQUEST                    5
#define DOT11_WFD_STATUS_FAILED_PREVIOUS_PROTOCOL_ERROR                         6
#define DOT11_WFD_STATUS_FAILED_NO_COMMON_CHANNELS                              7
#define DOT11_WFD_STATUS_FAILED_UNKNOWN_WFD_GROUP                               8
#define DOT11_WFD_STATUS_FAILED_MATCHING_MAX_INTENT                             9
#define DOT11_WFD_STATUS_FAILED_INCOMPATIBLE_PROVISIONING_METHOD                10
#define DOT11_WFD_STATUS_FAILED_REJECTED_BY_USER                                11

// WFD Minor Reason Code
#define DOT11_WFD_MINOR_REASON_SUCCESS                                          0
#define DOT11_WFD_MINOR_REASON_DISASSOCIATED_FROM_WLAN_CROSS_CONNECTION_POLICY  1
#define DOT11_WFD_MINOR_REASON_DISASSOCIATED_NOT_MANAGED_INFRASTRUCTURE_CAPABLE 2
#define DOT11_WFD_MINOR_REASON_DISASSOCIATED_WFD_COEXISTENCE_POLICY             3
#define DOT11_WFD_MINOR_REASON_DISASSOCIATED_INFRASTRUCTURE_MANAGED_POLICY      4

// WPS Version Information
#define DOT11_WPS_VERSION_1_0 0x01
#define DOT11_WPS_VERSION_2_0 0x02

// WFD Group Capability Bits
#define DOT11_WFD_GROUP_CAPABILITY_NONE                                         0x00
#define DOT11_WFD_GROUP_CAPABILITY_GROUP_OWNER                                  0x01
#define DOT11_WFD_GROUP_CAPABILITY_PERSISTENT_GROUP                             0x02
#define DOT11_WFD_GROUP_CAPABILITY_GROUP_LIMIT_REACHED                          0x04
#define DOT11_WFD_GROUP_CAPABILITY_INTRABSS_DISTRIBUTION_SUPPORTED              0x08
#define DOT11_WFD_GROUP_CAPABILITY_CROSS_CONNECTION_SUPPORTED                   0x10
#define DOT11_WFD_GROUP_CAPABILITY_PERSISTENT_RECONNECT_SUPPORTED               0x20
#define DOT11_WFD_GROUP_CAPABILITY_IN_GROUP_FORMATION                           0x40
#define DOT11_WFD_GROUP_CAPABILITY_RESERVED_7                                   0x80


// Device Type
typedef struct _DOT11_WFD_DEVICE_TYPE
{
    USHORT  CategoryID;
    USHORT  SubCategoryID;
    UCHAR   OUI[4];
} DOT11_WFD_DEVICE_TYPE, * PDOT11_WFD_DEVICE_TYPE;


// WPS Device Name
#define DOT11_WPS_DEVICE_NAME_MAX_LENGTH   32      // 32 bytes
typedef struct _DOT11_WPS_DEVICE_NAME {
#ifndef __midl
    _Field_range_(0,32)
#endif
    ULONG uDeviceNameLength;
    UCHAR ucDeviceName[DOT11_WPS_DEVICE_NAME_MAX_LENGTH];
} DOT11_WPS_DEVICE_NAME, * PDOT11_WPS_DEVICE_NAME;


// WFD Configuration Timeout
typedef 
struct _DOT11_WFD_CONFIGURATION_TIMEOUT
{
    UCHAR GOTimeout;	// Milliseconds
    UCHAR ClientTimeout;
} DOT11_WFD_CONFIGURATION_TIMEOUT, * PDOT11_WFD_CONFIGURATION_TIMEOUT;


// WFD Group ID
typedef 
struct _DOT11_WFD_GROUP_ID 
{
    DOT11_MAC_ADDRESS DeviceAddress;
    DOT11_SSID SSID;	
} DOT11_WFD_GROUP_ID, * PDOT11_WFD_GROUP_ID;


// WFD Group Owner Intent
typedef 
struct _DOT11_WFD_GO_INTENT 
{
    UCHAR TieBreaker:1;
    UCHAR Intent:7;
} DOT11_WFD_GO_INTENT, * PDOT11_WFD_GO_INTENT;


// WFD Channel
typedef 
struct _DOT11_WFD_CHANNEL 
{
    DOT11_COUNTRY_OR_REGION_STRING CountryRegionString;
    UCHAR OperatingClass;
    UCHAR ChannelNumber;
} DOT11_WFD_CHANNEL, * PDOT11_WFD_CHANNEL;


// WPS Config Method
typedef enum _DOT11_WPS_CONFIG_METHOD 
{
    DOT11_WPS_CONFIG_METHOD_NULL = 0,
    DOT11_WPS_CONFIG_METHOD_DISPLAY = 0x0008,
    DOT11_WPS_CONFIG_METHOD_PUSHBUTTON = 0x0080,
    DOT11_WPS_CONFIG_METHOD_KEYPAD = 0x0100
} DOT11_WPS_CONFIG_METHOD, *PDOT11_WPS_CONFIG_METHOD;


// WPS Device Password ID
typedef enum _DOT11_WPS_DEVICE_PASSWORD_ID 
{
    DOT11_WPS_PASSWORD_ID_DEFAULT = 0x0000,
    DOT11_WPS_PASSWORD_ID_USER_SPECIFIED = 0x0001,
    DOT11_WPS_PASSWORD_ID_MACHINE_SPECIFIED = 0x0002,
    DOT11_WPS_PASSWORD_ID_REKEY = 0x0003,
    DOT11_WPS_PASSWORD_ID_PUSHBUTTON = 0x0004,
    DOT11_WPS_PASSWORD_ID_REGISTRAR_SPECIFIED = 0x0005,
    // 0x0006 - 0x000F = Reserved
} DOT11_WPS_DEVICE_PASSWORD_ID, *PDOT11_WPS_DEVICE_PASSWORD_ID;


// NDIS indications for WFD mode.

// Data Type for NDIS_STATUS_DOT11_WFD_DISCOVER_COMPLETE 
#define DOT11_WFD_DISCOVER_COMPLETE_PARAMETERS_REVISION_1    1

#define DOT11_WFD_DISCOVER_COMPLETE_MAX_LIST_SIZE   128

    typedef 
    struct _DOT11_WFD_DISCOVER_COMPLETE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        NDIS_STATUS Status;
        ULONG uNumOfEntries;
        ULONG uTotalNumOfEntries;
        ULONG uListOffset;
        ULONG uListLength;
    } DOT11_WFD_DISCOVER_COMPLETE_PARAMETERS, * PDOT11_WFD_DISCOVER_COMPLETE_PARAMETERS;

#define DOT11_SIZEOF_WFD_DISCOVER_COMPLETE_PARAMETERS_REVISION_1 sizeof(DOT11_WFD_DISCOVER_COMPLETE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_GO_NEGOTIATION_REQUEST_SEND_COMPLETE
#define DOT11_GO_NEGOTIATION_REQUEST_SEND_COMPLETE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_GO_NEGOTIATION_REQUEST_SEND_COMPLETE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        NDIS_STATUS Status;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_GO_NEGOTIATION_REQUEST_SEND_COMPLETE_PARAMETERS, * PDOT11_GO_NEGOTIATION_REQUEST_SEND_COMPLETE_PARAMETERS;

#define DOT11_SIZEOF_GO_NEGOTIATION_REQUEST_SEND_COMPLETE_PARAMETERS_REVISION_1 sizeof(DOT11_GO_NEGOTIATION_REQUEST_SEND_COMPLETE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_RECEIVED_GO_NEGOTIATION_REQUEST
#define DOT11_RECEIVED_GO_NEGOTIATION_REQUEST_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_RECEIVED_GO_NEGOTIATION_REQUEST_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        PVOID RequestContext;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_RECEIVED_GO_NEGOTIATION_REQUEST_PARAMETERS, * PDOT11_RECEIVED_GO_NEGOTIATION_REQUEST_PARAMETERS;
    
#define DOT11_SIZEOF_RECEIVED_GO_NEGOTIATION_REQUEST_PARAMETERS_REVISION_1 sizeof(DOT11_RECEIVED_GO_NEGOTIATION_REQUEST_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE
#define DOT11_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        NDIS_STATUS Status;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE_PARAMETERS, * PDOT11_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE_PARAMETERS;

#define DOT11_SIZEOF_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE_PARAMETERS_REVISION_1 sizeof(DOT11_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_RECEIVED_GO_NEGOTIATION_RESPONSE
#define DOT11_RECEIVED_GO_NEGOTIATION_RESPONSE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_RECEIVED_GO_NEGOTIATION_RESPONSE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        PVOID ResponseContext;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_RECEIVED_GO_NEGOTIATION_RESPONSE_PARAMETERS, * PDOT11_RECEIVED_GO_NEGOTIATION_RESPONSE_PARAMETERS;
    
#define DOT11_SIZEOF_RECEIVED_GO_NEGOTIATION_RESPONSE_PARAMETERS_REVISION_1 sizeof(DOT11_RECEIVED_GO_NEGOTIATION_RESPONSE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE
#define DOT11_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        NDIS_STATUS Status;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE_PARAMETERS, * PDOT11_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE_PARAMETERS;

#define DOT11_SIZEOF_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE_PARAMETERS_REVISION_1 sizeof(DOT11_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_RECEIVED_GO_NEGOTIATION_CONFIRMATION
#define DOT11_RECEIVED_GO_NEGOTIATION_CONFIRMATION_PARAMETERS_REVISION_1    1    
    typedef 
    struct _DOT11_RECEIVED_GO_NEGOTIATION_CONFIRMATION_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_RECEIVED_GO_NEGOTIATION_CONFIRMATION_PARAMETERS, * PDOT11_RECEIVED_GO_NEGOTIATION_CONFIRMATION_PARAMETERS;
    
#define DOT11_SIZEOF_RECEIVED_GO_NEGOTIATION_CONFIRMATION_PARAMETERS_REVISION_1 sizeof(DOT11_RECEIVED_GO_NEGOTIATION_CONFIRMATION_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_INVITATION_REQUEST_SEND_COMPLETE
#define DOT11_INVITATION_REQUEST_SEND_COMPLETE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_INVITATION_REQUEST_SEND_COMPLETE_PARAMETERS
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_MAC_ADDRESS ReceiverAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        NDIS_STATUS Status;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_INVITATION_REQUEST_SEND_COMPLETE_PARAMETERS, * PDOT11_INVITATION_REQUEST_SEND_COMPLETE_PARAMETERS;
    
#define DOT11_SIZEOF_INVITATION_REQUEST_SEND_COMPLETE_PARAMETERS_REVISION_1 sizeof(DOT11_INVITATION_REQUEST_SEND_COMPLETE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_RECEIVED_INVITATION_REQUEST
#define DOT11_RECEIVED_INVITATION_REQUEST_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_RECEIVED_INVITATION_REQUEST_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS TransmitterDeviceAddress;
        DOT11_MAC_ADDRESS BSSID;
        DOT11_DIALOG_TOKEN DialogToken;
        PVOID RequestContext;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_RECEIVED_INVITATION_REQUEST_PARAMETERS, * PDOT11_RECEIVED_INVITATION_REQUEST_PARAMETERS;
    
#define DOT11_SIZEOF_RECEIVED_INVITATION_REQUEST_PARAMETERS_REVISION_1 sizeof(DOT11_RECEIVED_INVITATION_REQUEST_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_INVITATION_RESPONSE_SEND_COMPLETE
#define DOT11_INVITATION_RESPONSE_SEND_COMPLETE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_INVITATION_RESPONSE_SEND_COMPLETE_PARAMETERS
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS ReceiverDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        NDIS_STATUS Status;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_INVITATION_RESPONSE_SEND_COMPLETE_PARAMETERS, * PDOT11_INVITATION_RESPONSE_SEND_COMPLETE_PARAMETERS;
    
#define DOT11_SIZEOF_INVITATION_RESPONSE_SEND_COMPLETE_PARAMETERS_REVISION_1 sizeof(DOT11_INVITATION_RESPONSE_SEND_COMPLETE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_RECEIVED_INVITATION_RESPONSE
#define DOT11_RECEIVED_INVITATION_RESPONSE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_RECEIVED_INVITATION_RESPONSE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS TransmitterDeviceAddress;
        DOT11_MAC_ADDRESS BSSID;
        DOT11_DIALOG_TOKEN DialogToken;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_RECEIVED_INVITATION_RESPONSE_PARAMETERS, * PDOT11_RECEIVED_INVITATION_RESPONSE_PARAMETERS;
    
#define DOT11_SIZEOF_RECEIVED_INVITATION_RESPONSE_PARAMETERS_REVISION_1 sizeof(DOT11_RECEIVED_INVITATION_RESPONSE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE
#define DOT11_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE_PARAMETERS
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_MAC_ADDRESS ReceiverAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        NDIS_STATUS Status;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE_PARAMETERS, * PDOT11_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE_PARAMETERS;
    
#define DOT11_SIZEOF_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE_PARAMETERS_REVISION_1 sizeof(DOT11_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_RECEIVED_PROVISION_DISCOVERY_REQUEST
#define DOT11_RECEIVED_PROVISION_DISCOVERY_REQUEST_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_RECEIVED_PROVISION_DISCOVERY_REQUEST_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS TransmitterDeviceAddress;
        DOT11_MAC_ADDRESS BSSID;
        DOT11_DIALOG_TOKEN DialogToken;
        PVOID RequestContext;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_RECEIVED_PROVISION_DISCOVERY_REQUEST_PARAMETERS, * PDOT11_RECEIVED_PROVISION_DISCOVERY_REQUEST_PARAMETERS;
    
#define DOT11_SIZEOF_RECEIVED_PROVISION_DISCOVERY_REQUEST_PARAMETERS_REVISION_1 sizeof(DOT11_RECEIVED_PROVISION_DISCOVERY_REQUEST_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE
#define DOT11_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE_PARAMETERS
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS ReceiverDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        NDIS_STATUS Status;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE_PARAMETERS, * PDOT11_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE_PARAMETERS;
    
#define DOT11_SIZEOF_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE_PARAMETERS_REVISION_1 sizeof(DOT11_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_RECEIVED_PROVISION_DISCOVERY_RESPONSE
#define DOT11_RECEIVED_PROVISION_DISCOVERY_RESPONSE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_RECEIVED_PROVISION_DISCOVERY_RESPONSE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS TransmitterDeviceAddress;
        DOT11_MAC_ADDRESS BSSID;
        DOT11_DIALOG_TOKEN DialogToken;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_RECEIVED_PROVISION_DISCOVERY_RESPONSE_PARAMETERS, * PDOT11_RECEIVED_PROVISION_DISCOVERY_RESPONSE_PARAMETERS;
    
#define DOT11_SIZEOF_RECEIVED_PROVISION_DISCOVERY_RESPONSE_PARAMETERS_REVISION_1 sizeof(DOT11_RECEIVED_PROVISION_DISCOVERY_RESPONSE_PARAMETERS)


// Data Type for NDIS_STATUS_DOT11_WFD_GROUP_OPERATING_CHANNEL
// DOT11_WFD_CHANNEL structure is used by this indication



// TAG for WFD device specific OIDs.
#define NWF_WFD_DEVICE_OID  (0x05U) 

// TAG for WFD role (GO/Client) specific OIDs.
#define NWF_WFD_ROLE_OID    (0x06U) 


// OID_DOT11_WFD_DEVICE_CAPABILITY
#define OID_DOT11_WFD_DEVICE_CAPABILITY             NWF_DEFINE_OID(0x01,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_WFD_DEVICE_CAPABILITY_CONFIG_REVISION_1   1
    typedef 
    struct _DOT11_WFD_DEVICE_CAPABILITY_CONFIG  
    {
        NDIS_OBJECT_HEADER Header;
        BOOLEAN bServiceDiscoveryEnabled;
        BOOLEAN bClientDiscoverabilityEnabled;
        BOOLEAN bConcurrentOperationSupported;
        BOOLEAN bInfrastructureManagementEnabled;
        BOOLEAN bDeviceLimitReached;
        BOOLEAN bInvitationProcedureEnabled;
        ULONG WPSVersionsEnabled;
    } DOT11_WFD_DEVICE_CAPABILITY_CONFIG, * PDOT11_WFD_DEVICE_CAPABILITY_CONFIG;
    
#define DOT11_SIZEOF_WFD_DEVICE_CAPABILITY_CONFIG_1 sizeof(DOT11_WFD_DEVICE_CAPABILITY_CONFIG)


// OID_DOT11_WFD_GROUP_OWNER_CAPABILITY
#define OID_DOT11_WFD_GROUP_OWNER_CAPABILITY              NWF_DEFINE_OID(0x02,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_WFD_GROUP_OWNER_CAPABILITY_CONFIG_REVISION_1    1
    typedef 
    struct _DOT11_WFD_GROUP_OWNER_CAPABILITY_CONFIG 
    {
        NDIS_OBJECT_HEADER Header;
        BOOLEAN bPersistentGroupEnabled;
        BOOLEAN bIntraBSSDistributionSupported;
        BOOLEAN bCrossConnectionSupported;
        BOOLEAN bPersistentReconnectSupported;
        BOOLEAN bGroupFormationEnabled;
        ULONG uMaximumGroupLimit;
    } DOT11_WFD_GROUP_OWNER_CAPABILITY_CONFIG, *PDOT11_WFD_GROUP_OWNER_CAPABILITY_CONFIG;
    
#define DOT11_SIZEOF_WFD_GROUP_CAPABILITY_CONFIG_1  sizeof(DOT11_WFD_GROUP_OWNER_CAPABILITY_CONFIG)


// OID_DOT11_WFD_DEVICE_INFO
#define OID_DOT11_WFD_DEVICE_INFO                   NWF_DEFINE_OID(0x03,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_WFD_DEVICE_INFO_REVISION_1            1
    typedef 
    struct _DOT11_WFD_DEVICE_INFO 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS DeviceAddress;
        USHORT ConfigMethods;
        DOT11_WFD_DEVICE_TYPE PrimaryDeviceType;
        DOT11_WPS_DEVICE_NAME DeviceName;
    } DOT11_WFD_DEVICE_INFO, *PDOT11_WFD_DEVICE_INFO;
    
#define DOT11_SIZEOF_WFD_DEVICE_INFO_REVISION_1     sizeof(DOT11_WFD_DEVICE_INFO)


// OID_DOT11_WFD_SECONDARY_DEVICE_TYPE_LIST
#define OID_DOT11_WFD_SECONDARY_DEVICE_TYPE_LIST    NWF_DEFINE_OID(0x04,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_WFD_SECONDARY_DEVICE_TYPE_LIST_REVISION_1     1
    typedef 
    struct _DOT11_WFD_SECONDARY_DEVICE_TYPE_LIST {	
        NDIS_OBJECT_HEADER Header;
        ULONG uNumOfEntries;
        ULONG uTotalNumOfEntries;
        DOT11_WFD_DEVICE_TYPE SecondaryDeviceTypes[1];
    } DOT11_WFD_SECONDARY_DEVICE_TYPE_LIST, * PDOT11_WFD_SECONDARY_DEVICE_TYPE_LIST;
    
#define DOT11_SIZEOF_WFD_SECONDARY_DEVICE_TYPE_LIST_REVISION_1  FIELD_OFFSET(DOT11_WFD_SECONDARY_DEVICE_TYPE_LIST, SecondaryDeviceTypes)


// OID_DOT11_WFD_DISCOVER_REQUEST
#define OID_DOT11_WFD_DISCOVER_REQUEST          NWF_DEFINE_OID(0x05,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

    typedef enum _DOT11_WFD_DISCOVER_TYPE
    {
        dot11_wfd_discover_type_scan_only = 1,
        dot11_wfd_discover_type_find_only = 2,
        dot11_wfd_discover_type_auto = 3,
        dot11_wfd_discover_type_scan_social_channels = 4,
        dot11_wfd_discover_type_forced = 0x80000000
    
    } DOT11_WFD_DISCOVER_TYPE, *PDOT11_WFD_DISCOVER_TYPE;

    typedef enum _DOT11_WFD_SCAN_TYPE
    {
        dot11_wfd_scan_type_active = 1,
        dot11_wfd_scan_type_passive = 2,
        dot11_wfd_scan_type_auto = 3
    
    } DOT11_WFD_SCAN_TYPE, *PDOT11_WFD_SCAN_TYPE;

#define DOT11_WFD_DISCOVER_DEVICE_FILTER_REVISION_1
#define DOT11_SIZEOF_WFD_DISCOVER_DEVICE_FILTER_REVISION_1

#define DISCOVERY_FILTER_BITMASK_DEVICE 0x1
#define DISCOVERY_FILTER_BITMASK_GO     0x2
#define DISCOVERY_FILTER_BITMASK_ANY    0xF

    typedef 
    struct _DOT11_WFD_DISCOVER_DEVICE_FILTER
    {
        DOT11_MAC_ADDRESS DeviceID;
        UCHAR ucBitmask;
        DOT11_SSID GroupSSID;
    } DOT11_WFD_DISCOVER_DEVICE_FILTER, *PDOT11_WFD_DISCOVER_DEVICE_FILTER;

#define DOT11_WFD_DISCOVER_REQUEST_REVISION_1   1

    typedef 
    struct _DOT11_WFD_DISCOVER_REQUEST 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_WFD_DISCOVER_TYPE DiscoverType;
        DOT11_WFD_SCAN_TYPE ScanType;
        ULONG uDiscoverTimeout;
        ULONG uDeviceFilterListOffset;
        ULONG uNumDeviceFilters;
        ULONG uIEsOffset;
        ULONG uIEsLength;
        BOOLEAN bForceScanLegacyNetworks;
    } DOT11_WFD_DISCOVER_REQUEST, *PDOT11_WFD_DISCOVER_REQUEST;
    
#define DOT11_SIZEOF_WFD_DISCOVER_REQUEST_REVISION_1    sizeof(DOT11_WFD_DISCOVER_REQUEST) 

// OID_DOT11_WFD_ENUM_DEVICE_LIST
#define OID_DOT11_WFD_ENUM_DEVICE_LIST             NWF_DEFINE_OID(0x06,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)


//See comment about DOT11_BSS_ENTRY_PHY_SPECIFIC_INFO above
#ifndef __midl

#define DOT11_DEVICE_ENTRY_BYTE_ARRAY_REVISION_1    1
    typedef 
    struct _DOT11_WFD_DEVICE_ENTRY 
    {
        ULONG uPhyId;
        DOT11_BSS_ENTRY_PHY_SPECIFIC_INFO PhySpecificInfo;
        DOT11_MAC_ADDRESS dot11BSSID;
        DOT11_BSS_TYPE dot11BSSType;
        DOT11_MAC_ADDRESS TransmitterAddress;
        LONG lRSSI;
        ULONG uLinkQuality;
        USHORT usBeaconPeriod;
        ULONGLONG ullTimestamp;
        ULONGLONG ullBeaconHostTimestamp;
        ULONGLONG ullProbeResponseHostTimestamp;
        USHORT usCapabilityInformation;
        ULONG uBeaconIEsOffset;
        ULONG uBeaconIEsLength;	// Can be 0
        ULONG uProbeResponseIEsOffset;
        ULONG uProbeResponseIEsLength;	// Can be 0
    } DOT11_WFD_DEVICE_ENTRY, *PDOT11_WFD_DEVICE_ENTRY;

#endif

#define DOT11_WFD_DEVICE_ENTRY_GET_DEVICE_SIZE(_device_) \
        (sizeof(DOT11_WFD_DEVICE_ENTRY) + (_device_)->uBeaconIEsLength + (_device_)-> uProbeResponseIEsLength)

// OID_DOT11_WFD_LISTEN_STATE_DISCOVERABILITY
#define OID_DOT11_WFD_LISTEN_STATE_DISCOVERABILITY  NWF_DEFINE_OID(0x07,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)
    // ULONG
    #define DOT11_WFD_DEVICE_NOT_DISCOVERABLE   0
    #define DOT11_WFD_DEVICE_AUTO_AVAILABILITY  16
    #define DOT11_WFD_DEVICE_HIGH_AVAILABILITY  24


// OID_DOT11_WFD_ADDITIONAL_IE
#define OID_DOT11_WFD_ADDITIONAL_IE                 NWF_DEFINE_OID(0x08,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_WFD_ADDITIONAL_IE_REVISION_1          1
    typedef 
    struct _DOT11_WFD_ADDITIONAL_IE 
    {
        NDIS_OBJECT_HEADER Header;
        ULONG uBeaconIEsOffset;
        ULONG uBeaconIEsLength;
        ULONG uProbeResponseIEsOffset;
        ULONG uProbeResponseIEsLength;
        ULONG uDefaultRequestIEsOffset;
        ULONG uDefaultRequestIEsLength;

    } DOT11_WFD_ADDITIONAL_IE,
    *PDOT11_WFD_ADDITIONAL_IE;

#define DOT11_SIZEOF_WFD_ADDITIONAL_IE_REVISION_1   sizeof(DOT11_WFD_ADDITIONAL_IE)

#define DOT11_WFD_ADDITIONAL_IE_GET_HEADER_SIZE(_addie_) \
        (sizeof(DOT11_WFD_ADDITIONAL_IE))

#define DOT11_WFD_ADDITIONAL_IE_GET_HEADER_END(_addie_) \
        (((PCHAR)(_addie_))+sizeof(DOT11_WFD_ADDITIONAL_IE))

#define DOT11_WFD_ADDITIONAL_IE_GET_BEACON_IE(_addie_) \
        (((PCHAR)(_addie_))+(_addie_)->uBeaconIEsOffset)

#define DOT11_WFD_ADDITIONAL_IE_SET_BEACON_IE(_addie_, _beacon_) \
        (_addie_)->uBeaconIEsOffset = (DWORD)(((SIZE_T)(_beacon_))-((SIZE_T)(_addie_)))

#define DOT11_WFD_ADDITIONAL_IE_GET_BEACON_IE_SIZE(_addie_) \
        ((_addie_)->uBeaconIEsLength)

#define DOT11_WFD_ADDITIONAL_IE_SET_BEACON_IE_SIZE(_addie_, _size_) \
        (_addie_)->uBeaconIEsLength = (DWORD)(_size_)

#define DOT11_WFD_ADDITIONAL_IE_GET_BEACON_IE_END(_addie_) \
        (((PCHAR)(_addie_))+(_addie_)->uBeaconIEsOffset+DOT11_WFD_ADDITIONAL_IE_GET_BEACON_IE_SIZE(_addie_))

#define DOT11_WFD_ADDITIONAL_IE_GET_PROBE_RESPONSE_IE(_addie_) \
        (((PCHAR)(_addie_))+(_addie_)->uProbeResponseIEsOffset)

#define DOT11_WFD_ADDITIONAL_IE_SET_PROBE_RESPONSE_IE(_addie_, _response_) \
        (_addie_)->uProbeResponseIEsOffset = (DWORD)(((SIZE_T)(_response_))-((SIZE_T)(_addie_)))

#define DOT11_WFD_ADDITIONAL_IE_GET_PROBE_RESPONSE_IE_SIZE(_addie_) \
        ((_addie_)->uProbeResponseIEsLength)

#define DOT11_WFD_ADDITIONAL_IE_SET_PROBE_RESPONSE_IE_SIZE(_addie_, _size_) \
        (_addie_)->uProbeResponseIEsLength = (DWORD)(_size_)

#define DOT11_WFD_ADDITIONAL_IE_GET_PROBE_RESPONSE_IE_END(_addie_) \
        (((PCHAR)(_addie_))+(_addie_)->uProbeResponseIEsOffset+DOT11_WFD_ADDITIONAL_IE_GET_PROBE_RESPONSE_IE_SIZE(_addie_))

#define DOT11_WFD_ADDITIONAL_IE_GET_PROBE_REQUEST_IE(_addie_) \
        (((PCHAR)(_addie_))+(_addie_)->uDefaultRequestIEsOffset)

#define DOT11_WFD_ADDITIONAL_IE_SET_PROBE_REQUEST_IE(_addie_, _request_) \
        (_addie_)->uDefaultRequestIEsOffset = (DWORD)(((SIZE_T)(_request_))-((SIZE_T)(_addie_)))

#define DOT11_WFD_ADDITIONAL_IE_GET_PROBE_REQUEST_IE_SIZE(_addie_) \
        ((_addie_)->uDefaultRequestIEsLength)

#define DOT11_WFD_ADDITIONAL_IE_SET_PROBE_REQUEST_IE_SIZE(_addie_, _size_) \
        (_addie_)->uDefaultRequestIEsLength = (DWORD)(_size_)

#define DOT11_WFD_ADDITIONAL_IE_GET_ALL_IE_SIZE(_addie_) \
        ((_addie_)->uBeaconIEsLength + \
         (_addie_)->uProbeResponseIEsLength + \
         (_addie_)->uDefaultRequestIEsLength)

#define DOT11_WFD_ADDITIONAL_IE_GET_TOTAL_SIZE(_addie_) \
        (DOT11_WFD_ADDITIONAL_IE_GET_HEADER_SIZE(_addie_) + \
         DOT11_WFD_ADDITIONAL_IE_GET_ALL_IE_SIZE(_addie_))

// OID_DOT11_WFD_FLUSH_DEVICE_LIST
#define OID_DOT11_WFD_FLUSH_DEVICE_LIST             NWF_DEFINE_OID(0x09,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)
// No data


// OID_DOT11_WFD_SEND_GO_NEGOTIATION_REQUEST
#define OID_DOT11_WFD_SEND_GO_NEGOTIATION_REQUEST       NWF_DEFINE_OID(0x0A,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_SEND_GO_NEGOTIATION_REQUEST_PARAMETERS_REVISION_1     1
    typedef 
    struct _DOT11_SEND_GO_NEGOTIATION_REQUEST_PARAMETERS
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        ULONG uSendTimeout;
        DOT11_WFD_GO_INTENT GroupOwnerIntent;
        DOT11_WFD_CONFIGURATION_TIMEOUT MinimumConfigTimeout;
        DOT11_MAC_ADDRESS IntendedInterfaceAddress;
        DOT11_WFD_GROUP_CAPABILITY GroupCapability;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_SEND_GO_NEGOTIATION_REQUEST_PARAMETERS, * PDOT11_SEND_GO_NEGOTIATION_REQUEST_PARAMETERS;

#define DOT11_SIZEOF_SEND_GO_NEGOTIATION_REQUEST_PARAMETERS_REVISION_1  sizeof(DOT11_SEND_GO_NEGOTIATION_REQUEST_PARAMETERS)


// OID_DOT11_WFD_SEND_GO_NEGOTIATION_RESPONSE
#define OID_DOT11_WFD_SEND_GO_NEGOTIATION_RESPONSE  NWF_DEFINE_OID(0x0B,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_SEND_GO_NEGOTIATION_RESPONSE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_SEND_GO_NEGOTIATION_RESPONSE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        PVOID RequestContext;
        ULONG uSendTimeout;
        DOT11_WFD_STATUS_CODE Status;
        DOT11_WFD_GO_INTENT GroupOwnerIntent;
        DOT11_WFD_CONFIGURATION_TIMEOUT MinimumConfigTimeout;
        DOT11_MAC_ADDRESS IntendedInterfaceAddress;
        DOT11_WFD_GROUP_CAPABILITY GroupCapability;
        DOT11_WFD_GROUP_ID GroupID;
        BOOLEAN bUseGroupID;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_SEND_GO_NEGOTIATION_RESPONSE_PARAMETERS, * PDOT11_SEND_GO_NEGOTIATION_RESPONSE_PARAMETERS;

#define DOT11_SIZEOF_SEND_GO_NEGOTIATION_RESPONSE_PARAMETERS_REVISION_1 sizeof(DOT11_SEND_GO_NEGOTIATION_RESPONSE_PARAMETERS)


// OID_DOT11_WFD_SEND_GO_NEGOTIATION_CONFIRMATION
#define OID_DOT11_WFD_SEND_GO_NEGOTIATION_CONFIRMATION NWF_DEFINE_OID(0x0C,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_SEND_GO_NEGOTIATION_CONFIRMATION_PARAMETERS_REVISION_1    1
    typedef struct _DOT11_SEND_GO_NEGOTIATION_CONFIRMATION_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        PVOID ResponseContext;
        ULONG uSendTimeout;
        DOT11_WFD_STATUS_CODE Status;
        DOT11_WFD_GROUP_CAPABILITY GroupCapability;
        DOT11_WFD_GROUP_ID GroupID;
        BOOLEAN bUseGroupID;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_SEND_GO_NEGOTIATION_CONFIRMATION_PARAMETERS, * PDOT11_SEND_GO_NEGOTIATION_CONFIRMATION_PARAMETERS;
#define DOT11_SIZEOF_SEND_GO_NEGOTIATION_CONFIRMATION_PARAMETERS_REVISION_1 sizeof(DOT11_SEND_GO_NEGOTIATION_CONFIRMATION_PARAMETERS)


// OID_DOT11_WFD_SEND_INVITATION_REQUEST
#define OID_DOT11_WFD_SEND_INVITATION_REQUEST           NWF_DEFINE_OID(0x0D,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

    typedef 
    struct _DOT11_WFD_INVITATION_FLAGS 
    {
        UCHAR InvitationType:1; // 0 = Join active group, 1 = Reinvoke
        UCHAR Reserved:7;
    } DOT11_WFD_INVITATION_FLAGS, * PDOT11_WFD_INVITATION_FLAGS;

#define DOT11_SEND_INVITATION_REQUEST_PARAMETERS_REVISION_1     1
    typedef 
    struct _DOT11_SEND_INVITATION_REQUEST_PARAMETERS
    { 
        NDIS_OBJECT_HEADER Header;
        DOT11_DIALOG_TOKEN DialogToken;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        ULONG uSendTimeout;
        DOT11_WFD_CONFIGURATION_TIMEOUT MinimumConfigTimeout;
        DOT11_WFD_INVITATION_FLAGS InvitationFlags;
        DOT11_MAC_ADDRESS GroupBSSID; 	// Optional
        BOOLEAN bUseGroupBSSID;
        DOT11_WFD_CHANNEL OperatingChannel;
        BOOLEAN bUseSpecifiedOperatingChannel;
        DOT11_WFD_GROUP_ID GroupID;
        BOOLEAN bLocalGO;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_SEND_INVITATION_REQUEST_PARAMETERS, * PDOT11_SEND_INVITATION_REQUEST_PARAMETERS;

#define DOT11_SIZEOF_SEND_INVITATION_REQUEST_PARAMETERS_REVISION_1  sizeof(DOT11_SEND_INVITATION_REQUEST_PARAMETERS)


// OID_DOT11_WFD_SEND_INVITATION_RESPONSE
#define OID_DOT11_WFD_SEND_INVITATION_RESPONSE  NWF_DEFINE_OID(0x0E,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_SEND_INVITATION_RESPONSE_PARAMETERS_REVISION_1    1
    typedef 
    struct _DOT11_SEND_INVITATION_RESPONSE_PARAMETERS 
    {
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS ReceiverDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        PVOID RequestContext;
        ULONG uSendTimeout;
        DOT11_WFD_STATUS_CODE Status;
        DOT11_WFD_CONFIGURATION_TIMEOUT MinimumConfigTimeout;
        DOT11_MAC_ADDRESS GroupBSSID;	// Optional
        BOOLEAN bUseGroupBSSID;
        DOT11_WFD_CHANNEL OperatingChannel;
        BOOLEAN bUseSpecifiedOperatingChannel;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_SEND_INVITATION_RESPONSE_PARAMETERS, * PDOT11_SEND_INVITATION_RESPONSE_PARAMETERS;
    
#define DOT11_SIZEOF_SEND_INVITATION_RESPONSE_PARAMETERS_REVISION_1 sizeof(DOT11_SEND_INVITATION_RESPONSE_PARAMETERS)


// OID_DOT11_WFD_SEND_PROVISION_DISCOVERY_REQUEST
#define OID_DOT11_WFD_SEND_PROVISION_DISCOVERY_REQUEST  NWF_DEFINE_OID(0x0F,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_SEND_PROVISION_DISCOVERY_REQUEST_PARAMETERS_REVISION_1     1
    typedef 
    struct _DOT11_SEND_PROVISION_DISCOVERY_REQUEST_PARAMETERS
    { 
        NDIS_OBJECT_HEADER Header;
        DOT11_DIALOG_TOKEN DialogToken;
        DOT11_MAC_ADDRESS PeerDeviceAddress;
        ULONG uSendTimeout;
        DOT11_WFD_GROUP_CAPABILITY GroupCapability;
        DOT11_WFD_GROUP_ID GroupID;
        BOOLEAN bUseGroupID;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_SEND_PROVISION_DISCOVERY_REQUEST_PARAMETERS, * PDOT11_SEND_PROVISION_DISCOVERY_REQUEST_PARAMETERS;

#define DOT11_SIZEOF_SEND_PROVISION_DISCOVERY_REQUEST_PARAMETERS_REVISION_1  sizeof(DOT11_SEND_PROVISION_DISCOVERY_REQUEST_PARAMETERS)


// OID_DOT11_WFD_SEND_PROVISION_DISCOVERY_RESPONSE
#define OID_DOT11_WFD_SEND_PROVISION_DISCOVERY_RESPONSE NWF_DEFINE_OID(0x10,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

#define DOT11_SEND_PROVISION_DISCOVERY_RESPONSE_PARAMETERS_REVISION_1     1
    typedef 
    struct _DOT11_SEND_PROVISION_DISCOVERY_RESPONSE_PARAMETERS
    { 
        NDIS_OBJECT_HEADER Header;
        DOT11_MAC_ADDRESS ReceiverDeviceAddress;
        DOT11_DIALOG_TOKEN DialogToken;
        PVOID RequestContext;
        ULONG uSendTimeout;
        ULONG uIEsOffset;
        ULONG uIEsLength;
    } DOT11_SEND_PROVISION_DISCOVERY_RESPONSE_PARAMETERS, * PDOT11_SEND_PROVISION_DISCOVERY_RESPONSE_PARAMETERS;

#define DOT11_SIZEOF_SEND_PROVISION_DISCOVERY_RESPONSE_PARAMETERS_REVISION_1  sizeof(DOT11_SEND_PROVISION_DISCOVERY_RESPONSE_PARAMETERS)

// OID_DOT11_WFD_GET_DIALOG_TOKEN
#define OID_DOT11_WFD_GET_DIALOG_TOKEN       NWF_DEFINE_OID(0x11,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)
// DOT11_DIALOG_TOKEN

// OID_DOT11_WFD_STOP_DISCOVERY
#define OID_DOT11_WFD_STOP_DISCOVERY NWF_DEFINE_OID(0x12,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)

// OID_DOT11_WFD_DEVICE_LISTEN_CHANNEL
#define OID_DOT11_WFD_DEVICE_LISTEN_CHANNEL NWF_DEFINE_OID(0x13,NWF_WFD_DEVICE_OID,NWF_MANDATORY_OID)
#define DOT11_WFD_DEVICE_LISTEN_CHANNEL_REVISION_1  1
#define DOT11_SIZEOF_WFD_DEVICE_LISTEN_CHANNEL_REVISION_1 sizeof(DOT11_WFD_DEVICE_LISTEN_CHANNEL)
    typedef
    struct _DOT11_WFD_DEVICE_LISTEN_CHANNEL
    {
        NDIS_OBJECT_HEADER Header;
        UCHAR ChannelNumber;
    } DOT11_WFD_DEVICE_LISTEN_CHANNEL, *PDOT11_WFD_DEVICE_LISTEN_CHANNEL;


// OID_DOT11_WFD_DESIRED_GROUP_ID
#define OID_DOT11_WFD_DESIRED_GROUP_ID              NWF_DEFINE_OID(0x01,NWF_WFD_ROLE_OID,NWF_MANDATORY_OID)
// DOT11_WFD_GROUP_ID


// OID_DOT11_WFD_START_GO_REQUEST
#define OID_DOT11_WFD_START_GO_REQUEST                  NWF_DEFINE_OID(0x02,NWF_WFD_ROLE_OID,NWF_MANDATORY_OID)
// No data


// OID_DOT11_WFD_GROUP_START_PARAMETERS
#define OID_DOT11_WFD_GROUP_START_PARAMETERS            NWF_DEFINE_OID(0x03,NWF_WFD_ROLE_OID,NWF_MANDATORY_OID)

#define DOT11_WFD_GROUP_START_PARAMETERS_REVISION_1     1
    typedef 
    struct _DOT11_WFD_GROUP_START_PARAMETERS {	
        NDIS_OBJECT_HEADER Header;
        DOT11_WFD_CHANNEL AdvertisedOperatingChannel;
    } DOT11_WFD_GROUP_START_PARAMETERS, * PDOT11_WFD_GROUP_START_PARAMETERS;
    
#define DOT11_SIZEOF_WFD_GROUP_START_PARAMETERS_REVISION_1  sizeof(DOT11_WFD_GROUP_START_PARAMETERS)


// OID_DOT11_WFD_CONNECT_TO_GROUP_REQUEST
#define OID_DOT11_WFD_CONNECT_TO_GROUP_REQUEST          NWF_DEFINE_OID(0x04,NWF_WFD_ROLE_OID,NWF_MANDATORY_OID)
// No data


// OID_DOT11_WFD_DISCONNECT_FROM_GROUP_REQUEST
#define OID_DOT11_WFD_DISCONNECT_FROM_GROUP_REQUEST     NWF_DEFINE_OID(0x05,NWF_WFD_ROLE_OID,NWF_MANDATORY_OID)
// No data


// OID_DOT11_WFD_GROUP_JOIN_PARAMETERS
#define OID_DOT11_WFD_GROUP_JOIN_PARAMETERS             NWF_DEFINE_OID(0x06,NWF_WFD_ROLE_OID,NWF_MANDATORY_OID)

#define DOT11_WFD_GROUP_JOIN_PARAMETERS_REVISION_1      1
    typedef 
    struct _DOT11_WFD_GROUP_JOIN_PARAMETERS {	
        NDIS_OBJECT_HEADER Header;
        DOT11_WFD_CHANNEL GOOperatingChannel;
        ULONG GOConfigTime;
        BOOLEAN bInGroupFormation;
        BOOLEAN bWaitForWPSReady;
    } DOT11_WFD_GROUP_JOIN_PARAMETERS, * PDOT11_WFD_GROUP_JOIN_PARAMETERS;
    
#define DOT11_SIZEOF_WFD_GROUP_JOIN_PARAMETERS_REVISION_1  sizeof(DOT11_WFD_GROUP_JOIN_PARAMETERS)

#endif __WINDOT11_WFD_H__

